// الدفعة 9 — 100 slang + 110 idioms
S("Adulting","يمارس مسؤوليات الكبار","Paying bills is adulting.");
S("Alpha","شخص مسيطر وقيادي","He thinks he's an alpha.");
S("Awks","محرج (awkward)","That was so awks.");
S("Baddie","شخص واثق وجذاب","She's a total baddie.");
S("Bestie","أعز صديق","Hey, bestie!");
S("Big mood","شعور يتماهى معه الجميع","Napping all day, big mood.");
S("Blessed","محظوظ وشاكر","I'm feeling blessed.");
S("Boss","رائع","That's a boss move.");
S("Burner","هاتف مؤقت","He uses a burner phone.");
S("Catch feelings","يقع في الحب","I think I caught feelings.");
S("Chef's kiss","إتقان تام","The soup? Chef's kiss.");
S("Curve","يرفض بلطف","She curved him.");
S("Dap","مصافحة ودية","Give me a dap.");
S("Deep cut","أغنية أو معلومة غير مشهورة","That's a real deep cut.");
S("Doggo","كلب (بلطف)","Look at that doggo!");
S("Emo","شديد العاطفة","He's feeling emo today.");
S("Fandom","مجتمع المعجبين","The fandom is huge.");
S("Fanboy","معجب متحمس","He's a Marvel fanboy.");
S("Gaslight","يجعل غيره يشك في عقله","He gaslit her for years.");
S("Gold digger","من يرتبط من أجل المال","They called her a gold digger.");
S("Heated","غاضب أو محتدم","The debate got heated.");
S("Hipster","شخص يتبع الثقافة البديلة","He's such a hipster.");
S("Hottie","شخص جذاب","The barista is a hottie.");
S("Instagrammable","يستحق التصوير","This café is Instagrammable.");
S("IRL","في الحياة الحقيقية","We finally met IRL.");
S("Keeper","شيء أو شخص يستحق الاحتفاظ به","She's a keeper.");
S("Meme","صورة أو فكرة ساخرة منتشرة","That's a funny meme.");
S("NPC","شخص يتصرف بلا تفكير","He acts like an NPC.");
S("Nope","لا","Nope, not doing that.");
S("OOTD","إطلالة اليوم","Here's my OOTD.");
S("Overshare","يفصح عن معلومات خاصة","Sorry, I overshared.");
S("Peak","في ذروة الجودة","This pizza is peak.");
S("Pick-me","شخص يتصنع التميز لإرضاء غيره","She's a total pick-me.");
S("Plot twist","مفاجأة غير متوقعة","Plot twist: he quit.");
S("Pressed","منزعج","Why are you so pressed?");
S("Quirky","غريب بشكل لطيف","She's a quirky artist.");
S("Red flag","علامة تحذير","That's a red flag.");
S("Rent free","يشغل البال باستمرار","He lives in my head rent free.");
S("Sheesh","تعبير عن الدهشة","Sheesh, that's expensive!");
S("Side eye","نظرة استنكار","She gave me the side eye.");
S("Situationship","علاقة غير واضحة المعالم","It's just a situationship.");
S("Smol","صغير ولطيف","Look at this smol kitten.");
S("Spicy","جريء أو مثير للجدل","That's a spicy take.");
S("Stalk","يتتبع حسابات شخص","I stalked his profile.");
S("Swipe","يمرر الشاشة","I swiped left.");
S("Thirst trap","منشور يهدف لجذب الإعجاب","He posted a thirst trap.");
S("Trending","رائج","This song is trending.");
S("Viral","ينتشر بسرعة","The video went viral.");
S("W","فوز","That's a big W.");
S("Weird flex","تباهٍ غريب","Weird flex, but okay.");
S("Zaddy","رجل أنيق وجذاب","He's a total zaddy.");
S("Binge-watch","يشاهد حلقات متتالية","We binge-watched all season.");
S("Cheugy","قديم الموضة","That trend is cheugy.");
S("Lurk","يتابع دون مشاركة","I just lurk in the chat.");
S("Cringey","محرج (cringe)","That's so cringey.");
S("Bog roll","ورق الحمام","We're out of bog roll.","UK");
S("Bruv","أخي","Alright, bruv?","UK");
S("Cobblers","كلام فارغ","That's a load of cobblers.","UK");
S("Codswallop","هراء","What a load of codswallop!","UK");
S("Gammy","مصاب أو معطوب","I've got a gammy knee.","UK");
S("Grotty","قذر ورديء","It's a grotty little flat.","UK");
S("Jim-jams","بيجامة","Put your jim-jams on.","UK");
S("Knock off","ينهي عمله","I knock off at five.","UK");
S("Lark","مقلب أو مزحة","It was just a lark.","UK");
S("Local","الحانة المحلية","Let's go to the local.","UK");
S("Nana","جدة","Nana's baking biscuits.","UK");
S("On the dole","يتقاضى إعانة بطالة","He's been on the dole.","UK");
S("Prat","أحمق","I felt a right prat.","UK");
S("Quack","طبيب","I'll see the quack tomorrow.","UK");
S("Ruddy","لعين (تخفيف)","It's a ruddy mess.","UK");
S("Sarky","ساخر","Don't be sarky.","UK");
S("Shirty","غاضب","He got shirty with me.","UK");
S("Smarmy","متملق ولزج","He's so smarmy.","UK");
S("Snazzy","أنيق ولافت","That's a snazzy jacket.","UK");
S("Sod all","لا شيء إطلاقًا","There's sod all to do.","UK");
S("Spanner","شخص أحمق (أصل: مفتاح ربط)","Don't be a spanner.","UK");
S("Stroppy","مزاجي وعنيد","She's being stroppy.","UK");
S("Swanky","فخم","It's a swanky hotel.","UK");
S("Tosh","كلام فارغ","That's utter tosh.","UK");
S("Twee","متكلف الجمال","The café is a bit twee.","UK");
S("Wally","شخص أحمق","I felt like a wally.","UK");
S("Wangle","يحصل بحيلة","He wangled a free ticket.","UK");
S("Wobbly","غاضب أو غير ثابت","She threw a wobbly.","UK");
S("Mucker","صديق","Alright, mucker?","UK");
S("Pukka","أصيل وممتاز","That's a pukka curry.","UK");
S("Righto","حسنًا","Righto, let's go.","UK");
S("Sloshed","ثمل","He was totally sloshed.","UK");
S("Spot on","دقيق تمامًا","Your guess was spot on.","UK");
S("Sweet FA","لا شيء","I did sweet FA all day.","UK");
S("Tipsy","ثمل قليلًا","I'm a bit tipsy.","UK");
S("Top notch","في أعلى مستوى","It was top notch service.","UK");
S("Whizz","شخص بارع","He's a maths whizz.","UK");
S("Posh","راقٍ أو متكلف","They live in a posh area.","UK");
S("Mum","أمي","Ask your mum.","UK");
S("Crisps","رقائق البطاطس","A packet of crisps, please.","UK");
S("Fizzy","غازي","I don't like fizzy drinks.","UK");
S("Cheers","شكرًا أو في صحتك","Cheers for the lift!","UK");
S("Cheesed off","منزعج","I'm cheesed off with it.","UK");
S("Peeved","منزعج","She's a bit peeved.","UK");
S("Gubbins","أجزاء أو أشياء متفرقة","What are those gubbins?","UK");
I("A bitter pill to swallow","حقيقة مرّة","Defeat was a bitter pill to swallow.");
I("A closed book","شخص أو أمر غامض","He's a closed book to me.");
I("A drop in the bucket","كمية ضئيلة جدًا","It's just a drop in the bucket.");
I("A fool's paradise","وهم سعادة زائف","He lives in a fool's paradise.");
I("A matter of time","مسألة وقت","It's only a matter of time.");
I("A step in the right direction","خطوة إيجابية","It's a step in the right direction.");
I("A tough nut to crack","مشكلة أو شخص صعب","This problem is a tough nut to crack.");
I("A walk in the park","أمر سهل جدًا","The test was a walk in the park.");
I("Against the clock","في سباق مع الوقت","We worked against the clock.");
I("Ahead of the curve","سابق لعصره","The company is ahead of the curve.");
I("All in a day's work","أمر عادي في العمل","Saving lives is all in a day's work.");
I("All thumbs","أخرق اليدين","I'm all thumbs in the kitchen.");
I("An open secret","سر معروف للجميع","It's an open secret.");
I("An uphill battle","معركة صعبة","It's an uphill battle.");
I("Arm in arm","متشابكان بالأذرع","They walked arm in arm.");
I("As easy as pie","سهل جدًا","It's as easy as pie.");
I("As good as gold","مطيع جدًا","The kids were as good as gold.");
I("As right as rain","بخير تمامًا","I'll be as right as rain tomorrow.");
I("As old as the hills","قديم جدًا","That joke is as old as the hills.");
I("At a snail's pace","ببطء شديد","The traffic crawled at a snail's pace.");
I("At stake","معرّض للخطر","Our jobs are at stake.");
I("At the end of the day","في النهاية","At the end of the day, it's your choice.");
I("At your wits' end","نفد صبره وحيلته","I'm at my wits' end.");
I("A bag of nerves","شديد التوتر","She was a bag of nerves.");
I("Be my guest","تفضل","May I sit here? Be my guest.");
I("Bear with me","اصبر عليّ","Bear with me a moment.");
I("Beat the odds","يتغلب على الاحتمالات","He beat the odds.");
I("A bird's-eye view","نظرة شاملة","We got a bird's-eye view of the city.");
I("Blow the whistle","يكشف مخالفة","She blew the whistle on fraud.");
I("Bold as brass","جريء بوقاحة","He walked in bold as brass.");
I("Born and bred","وُلد ونشأ","I'm a Londoner born and bred.");
I("The bottom line","الخلاصة","The bottom line is we need money.");
I("Bounce back","يتعافى","She bounced back quickly.");
I("Break the news","يخبر بخبر","Who will break the news?");
I("Bring up the rear","يأتي في المؤخرة","He brought up the rear.");
I("A broken record","يكرر نفسه","You sound like a broken record.");
I("Brush up on","يراجع ويحسّن","I need to brush up on my French.");
I("Build castles in the air","يبني أحلامًا غير واقعية","Stop building castles in the air.");
I("Take the bull by the horns","يواجه الصعاب مباشرة","Take the bull by the horns.");
I("A burning question","سؤال ملحّ","Here's the burning question.");
I("Bury your head in the sand","يتجاهل المشكلة","Don't bury your head in the sand.");
I("Busy as a bee","مشغول جدًا","I've been busy as a bee.");
I("By leaps and bounds","بسرعة كبيرة","She's improving by leaps and bounds.");
I("Call off","يلغي","They called off the match.");
I("Call someone's bluff","يتحداه ليكشف خداعه","I called his bluff.");
I("The calm before the storm","هدوء يسبق العاصفة","It was the calm before the storm.");
I("Cat and mouse","لعبة مطاردة","They played cat and mouse.");
I("Catch someone off guard","يباغته","The question caught me off guard.");
I("Caught in the crossfire","عالق وسط الخصومة","I was caught in the crossfire.");
I("Chip in","يساهم بجزء","Let's all chip in.");
I("A clean sweep","فوز كامل","They made a clean sweep.");
I("Clear as mud","غامض جدًا","The instructions are clear as mud.");
I("Close to home","يمس الإنسان شخصيًا","That joke hit too close to home.");
I("Come up trumps","ينجح بشكل مفاجئ","He came up trumps.","UK");
I("Cut down to size","يخفض غروره","She cut him down to size.");
I("Dig your own grave","يتسبب بخرابه","He's digging his own grave.");
I("Dirt cheap","رخيص جدًا","The tickets were dirt cheap.");
I("Dog-eat-dog","تنافس شرس","It's a dog-eat-dog world.");
I("Dressed to the nines","في أبهى حلة","She was dressed to the nines.");
I("Drop in","يزور بلا موعد","Drop in anytime.");
I("A dry spell","فترة جفاف أو ركود","The team had a dry spell.");
I("Early days","البداية ولا يمكن الحكم بعد","It's early days yet.");
I("Easy come, easy go","ما يأتي بسهولة يذهب بسهولة","Easy come, easy go.");
I("Elbow grease","جهد عضلي","It needs some elbow grease.");
I("Face to face","وجهًا لوجه","We met face to face.");
I("Fair play","إنصاف أو تحية","Fair play to him.");
I("Fast track","مسار سريع","She's on the fast track.");
I("Fire up","يشعل الحماس","The speech fired up the crowd.");
I("Flat broke","مفلس تمامًا","I'm flat broke.");
I("With flying colors","بتفوق","She passed with flying colors.");
I("A fool's errand","مهمة عبثية","It was a fool's errand.");
I("Forgive and forget","يسامح وينسى","Let's forgive and forget.");
I("Free as a bird","حر تمامًا","I feel free as a bird.");
I("Gain ground","يحرز تقدمًا","The party is gaining ground.");
I("Get the picture","يفهم الصورة","Do you get the picture?");
I("Go for broke","يجازف بكل شيء","Let's go for broke.");
I("Go to town","يبالغ في الإنفاق أو الجهد","They went to town on decorations.");
I("Going strong","مستمر بقوة","She's 90 and still going strong.");
I("A gut feeling","حدس","I have a gut feeling about it.");
I("I'll hand it to you","أعترف بفضلك","I'll hand it to you, it worked.");
I("Handle with kid gloves","يعامل بحذر شديد","Handle him with kid gloves.");
I("No hard feelings","بلا ضغينة","No hard feelings, okay?");
I("Have a field day","يستمتع بفرصة كبيرة","The press had a field day.");
I("Have words","يتشاجران","We had words about it.");
I("Hell-bent on","مصمم بعناد على","He's hell-bent on winning.");
I("Hit home","يصيب الهدف عاطفيًا","Her words hit home.");
I("Hold your own","يثبت في المواجهة","She can hold her own.");
I("The home stretch","المرحلة الأخيرة","We're in the home stretch.");
