// الدفعة 8 — 100 slang + 100+ idioms
S("Aight","حسنًا (alright)","Aight, see you later.");
S("Bust","يكسر أو يضبط","The cops busted the party.");
S("Bye Felicia","وداعًا وتجاهل لك","He's leaving? Bye Felicia.");
S("Chillin'","يسترخي","I'm just chillin' at home.");
S("Cooked","في ورطة أو منتهٍ","If he sees this, I'm cooked.");
S("Dawg","صديق","What's up, dawg?");
S("Drama queen","شخص يبالغ في ردود فعله","Stop being a drama queen.");
S("Dumb","غبي أو سخيف","That was a dumb idea.");
S("Edgy","جريء وغير تقليدي","It's an edgy design.");
S("Finesse","يحقق شيئًا بمهارة ودهاء","He finessed his way in.");
S("Floss","يتباهى بثرائه","He's flossing his new car.");
S("Foodie","مولع بالطعام الجيد","I'm a total foodie.");
S("Frickin'","كلمة تأكيد مخففة","It's frickin' cold!");
S("Go off","يتكلم أو يتصرف بحماس وجرأة","Go off, queen!");
S("Grail","غاية يسعى إليها المقتني","These are my grail sneakers.");
S("Gucci","بخير وممتاز","Everything's Gucci.");
S("Gym rat","رواد النادي الدائمون","He's a gym rat.");
S("Hang tight","انتظر قليلًا","Hang tight, I'm coming.");
S("Homie","صديق مقرّب","He's my homie.");
S("Hypebeast","مهووس بالموضة الرائجة","He's a hypebeast.");
S("Influencer","مؤثر على الشبكات","She's a travel influencer.");
S("Jam out","يستمتع بالموسيقى","We jammed out all night.");
S("Kinda","نوعًا ما","It's kinda cold.");
S("Legend","شخص رائع","You're a legend!");
S("Mic drop","جملة قوية تنهي النقاش","That was a mic drop moment.");
S("Narc","من يشي بالآخرين","Don't be a narc.");
S("Neat","جميل وأنيق","That's a neat trick.");
S("Outta here","أنا راحل","I'm outta here.");
S("Playa","شخص يغازل كثيرًا","He's a playa.");
S("Poser","يتظاهر بما ليس فيه","He's such a poser.");
S("Preppy","أنيق على الطراز المدرسي","She's very preppy.");
S("Pump the brakes","تمهّل","Pump the brakes, we're not ready.");
S("Rage quit","ينسحب غاضبًا","He rage quit the game.");
S("Rekt","مهزوم تمامًا","We got rekt.");
S("Sassy","وقح بخفة ظل","She's a sassy kid.");
S("Scam","احتيال","It's a scam, don't pay.");
S("Scrub","شخص عديم المهارة","Stop playing like a scrub.");
S("Sesh","جلسة","We had a gaming sesh.");
S("Slob","شخص مهمل ومبعثر","He's a total slob.");
S("Smash","ينجح بقوة أو يأكل بشهية","I smashed that exam.");
S("Spaced out","شارد الذهن","I was spaced out in class.");
S("Stacks","أموال كثيرة","He's got stacks.");
S("Stressed","متوتر","I'm so stressed.");
S("Swole","مفتول العضلات","He got swole fast.");
S("TBH","بصراحة","TBH, I didn't like it.");
S("Toxic","سام ومؤذٍ","It's a toxic friendship.");
S("Trippin'","يتصرف بغرابة أو يبالغ","You're trippin' right now.");
S("Troll","يستفز عمدًا","He trolls people online.");
S("Wanna","أريد أن","Wanna grab a coffee?");
S("Wild","جنوني ومدهش","That was wild!");
S("Yass","تعبير عن الحماس","Yass, you got the job!");
S("Yo","مرحبًا","Yo, what's up?");
S("Zoned out","شارد الذهن","Sorry, I zoned out.");
S("Skrrt","صوت إطارات يعبّر عن الحماس","Skrrt! Let's go.");
S("Ain't","صيغة عامية للنفي","That ain't right.");
S("Aggro","عدواني أو مزعج","He gets aggro when he's angry.","UK");
S("Beano","وليمة أو حفلة","We had a beano at his house.","UK");
S("Boffin","عالم أو مهووس بالعلوم","He's a computer boffin.","UK");
S("Bolshy","متمرد","She's a bit bolshy.","UK");
S("Brassed off","غاضب","I'm brassed off with him.","UK");
S("Brass neck","وقاحة","He's got a brass neck.","UK");
S("Corking","ممتاز","That's a corking idea.","UK");
S("Dab hand","ماهر","She's a dab hand at baking.","UK");
S("Dishy","جذاب","The new teacher is dishy.","UK");
S("Dogsbody","شخص يؤدي الأعمال الشاقة","I'm just the office dogsbody.","UK");
S("Dozy","غافل وبطيء الفهم","Don't be so dozy.","UK");
S("Fella","رجل أو صديق","He's a nice fella.","UK");
S("Flat out","بأقصى سرعة","We're working flat out.","UK");
S("Flummoxed","محتار","I was totally flummoxed.","UK");
S("Gander","نظرة سريعة","Have a gander at this.","UK");
S("Gawp","يحدّق بذهول","They gawped at the car.","UK");
S("Hacked off","منزعج","I'm hacked off with the delay.","UK");
S("Hard cheese","حظ سيئ","Hard cheese, mate.","UK");
S("Hoot","شيء مضحك","The show was a hoot.","UK");
S("Jolly","جدًا","That's jolly good.","UK");
S("Meal deal","وجبة غداء بسعر مخفض","I got a meal deal.","UK");
S("Mug","شخص ساذج","He took me for a mug.","UK");
S("Nark","مخبر أو شخص مزعج","He's a nark.","UK");
S("Nosey parker","فضولي","Don't be a nosey parker.","UK");
S("Oik","شخص فظ","He's a rude oik.","UK");
S("Porkies","أكاذيب","He's telling porkies.","UK");
S("Quids in","رابح","If it works, we're quids in.","UK");
S("Ropey","رديء","The wifi is ropey.","UK");
S("Row","شجار صاخب","They had a row.","UK");
S("Rum","غريب","That's a rum business.","UK");
S("Scrummy","لذيذ","The cake was scrummy.","UK");
S("Scrounge","يتسول ويستجدي","He's always scrounging.","UK");
S("Shambles","فوضى كاملة","The event was a shambles.","UK");
S("Slap-up","فاخر (للوجبات)","We had a slap-up dinner.","UK");
S("Sod's law","كل ما قد يسوء سيسوء","It's Sod's law, it rained.","UK");
S("Spend a penny","يذهب إلى دورة المياه","I need to spend a penny.","UK");
S("Stonking","رائع جدًا","That was a stonking goal.","UK");
S("Sunnies","نظارات شمسية","Grab your sunnies.","UK");
S("Tickety-boo","على ما يرام","Everything's tickety-boo.","UK");
S("Toodle-oo","إلى اللقاء","Toodle-oo, see you soon!","UK");
S("Trainers","أحذية رياضية","New trainers, nice!","UK");
S("Turf","منطقة نفوذ","This is my turf.","UK");
S("Wind up","يستفز بالمزاح","Are you winding me up?","UK");
S("Yob","شاب فظ","A gang of yobs shouted.","UK");
S("Pop","مشروب غازي","Do you want some pop?","UK");
I("Keep at bay","يبقي بعيدًا","Garlic keeps vampires at bay.");
I("Keep someone posted","يبقيه على اطلاع","Keep me posted.");
I("Keep your cool","يحافظ على هدوئه","Keep your cool.");
I("Keep your fingers crossed","يتمنى الحظ","I'll keep my fingers crossed.");
I("Kick off","يبدأ","The meeting kicks off at nine.");
I("Kick up a fuss","يثير ضجة","Don't kick up a fuss.");
I("Kill time","يقتل الوقت","We played cards to kill time.");
I("Know the ropes","خبير بأساسيات العمل","She knows the ropes.");
I("Land on your feet","ينجو بحظ","He always lands on his feet.");
I("Leave someone in the lurch","يتركه في ورطة","He left me in the lurch.");
I("Let bygones be bygones","نسيان الماضي","Let bygones be bygones.");
I("Let off steam","يفرغ غضبه","He let off steam in the gym.");
I("A level playing field","فرص متكافئة","We want a level playing field.");
I("Lie low","يختبئ ويبقى هادئًا","We'll lie low for a while.");
I("Like father, like son","الولد سر أبيه","Like father, like son.");
I("Like two peas in a pod","متشابهان جدًا","They're like two peas in a pod.");
I("Live from hand to mouth","يعيش على الكفاف","They lived from hand to mouth.");
I("Lock horns","يتصارعان","The two managers locked horns.");
I("A long shot","احتمال ضعيف","It's a long shot, but try.");
I("Look on the bright side","انظر للجانب المشرق","Look on the bright side.");
I("Lose face","يفقد ماء وجهه","He didn't want to lose face.");
I("Lose heart","يفقد الأمل","Don't lose heart.");
I("Lose track of time","ينسى الوقت","I lost track of time.");
I("Make a scene","يثير فضيحة","Please don't make a scene.");
I("Make do","يتدبر بما هو متاح","We'll make do with what we have.");
I("Make waves","يسبب ضجة","She's making waves in tech.");
I("Mind over matter","الإرادة تتغلب على الألم","It's mind over matter.");
I("Miss the point","لا يفهم المغزى","You're missing the point.");
I("A mixed bag","خليط متفاوت","The results were a mixed bag.");
I("Move the goalposts","يغيّر الشروط","They keep moving the goalposts.");
I("My hands are tied","لا أستطيع التصرف","I'd help, but my hands are tied.");
I("Nothing ventured, nothing gained","من لا يجازف لا يربح","Nothing ventured, nothing gained.");
I("Odds and ends","أشياء متفرقة","It's a box of odds and ends.");
I("Off the cuff","ارتجالًا","He spoke off the cuff.");
I("Off the beaten track","بعيد عن الطرق المألوفة","We found a village off the beaten track.");
I("On a roll","في سلسلة نجاحات","The team is on a roll.");
I("On edge","متوتر","I'm on edge today.");
I("On pins and needles","في ترقب وقلق","We waited on pins and needles.");
I("On the back burner","مؤجل","The project is on the back burner.");
I("On the mend","يتعافى","He's on the mend.");
I("On the rocks","على وشك الانهيار","Their marriage is on the rocks.");
I("On top of the world","في قمة السعادة","I feel on top of the world.");
I("Once and for all","مرة وإلى الأبد","Let's settle this once and for all.");
I("A one-track mind","تفكير في أمر واحد","He has a one-track mind.");
I("Open a can of worms","يفتح موضوعًا شائكًا","That opens a can of worms.");
I("Out of order","معطل","The lift is out of order.");
I("Out of sorts","غير مرتاح","I'm feeling out of sorts.");
I("Out of touch","منقطع عن المستجدات","He's out of touch.");
I("Over the top","مبالغ فيه","His reaction was over the top.");
I("Paint the town red","يسهر ويستمتع","Let's paint the town red.");
I("Part and parcel","جزء لا يتجزأ","Stress is part and parcel of it.");
I("A pat on the back","كلمة ثناء","He deserves a pat on the back.");
I("Pecking order","التسلسل الهرمي","He's low in the pecking order.");
I("Pie in the sky","حلم بعيد المنال","That's just pie in the sky.");
I("A pipe dream","حلم غير واقعي","Owning an island is a pipe dream.");
I("Play it cool","يتظاهر بالهدوء","Just play it cool.");
I("Play with fire","يغامر بأمر خطر","You're playing with fire.");
I("Point the finger","يلقي اللوم","Don't point the finger at me.");
I("Pop the question","يطلب الزواج","He popped the question.");
I("Pour oil on troubled waters","يهدئ الخلاف","She poured oil on troubled waters.");
I("Pros and cons","الإيجابيات والسلبيات","Let's weigh the pros and cons.");
I("Pull your weight","يؤدي نصيبه من العمل","Everyone must pull their weight.");
I("Push the envelope","يتجاوز الحدود المعتادة","The designer pushes the envelope.");
I("Put on hold","يعلّق","We put the plan on hold.");
I("Put your feet up","يرتاح","Put your feet up for a bit.");
I("Quality time","وقت ممتع مع من تحب","We need more quality time.");
I("Raise the bar","يرفع المعيار","This film raises the bar.");
I("Rack your brain","يجهد ذهنه","I racked my brain for the answer.");
I("The rat race","سباق الحياة المرهق","I'm tired of the rat race.");
I("Ring a bell","يذكّر بشيء","That name rings a bell.");
I("Rise and shine","استيقظ ونشِط","Rise and shine, sleepyhead!");
I("Roll with the punches","يتكيف مع الصعوبات","You have to roll with the punches.");
I("Rough around the edges","غير مصقول","He's a bit rough around the edges.");
I("Run of the mill","عادي","It was a run-of-the-mill day.");
I("Safe and sound","سالم","They arrived safe and sound.");
I("Save face","يحفظ ماء وجهه","He lied to save face.");
I("Save your breath","وفّر كلامك","Save your breath, he won't listen.");
I("Second to none","لا مثيل له","Her skills are second to none.");
I("Set in stone","ثابت لا يتغير","Nothing is set in stone.");
I("Shoot the breeze","يتجاذب أطراف الحديث","We shot the breeze for hours.");
I("Show your true colors","يكشف حقيقته","He showed his true colors.");
I("Sink or swim","النجاح أو الفشل","It's sink or swim now.");
I("Sleep like a log","ينام عميقًا","I slept like a log.");
I("Smell a rat","يشك في أمر","I smell a rat.");
I("Spice things up","يضيف الحماس","Let's spice things up.");
I("Split hairs","يدقق في التفاصيل","Stop splitting hairs.");
I("Stick to your guns","يتمسك بموقفه","She stuck to her guns.");
I("Straight from the horse's mouth","من المصدر مباشرة","I heard it straight from the horse's mouth.");
I("Take it easy","خذ الأمر ببساطة","Take it easy, relax.");
I("Take for granted","يعتبره أمرًا مفروغًا منه","Don't take your family for granted.");
I("That's the way the cookie crumbles","هذه هي الحياة","Oh well, that's the way the cookie crumbles.");
I("The ins and outs","التفاصيل الدقيقة","He knows the ins and outs.");
I("The tables have turned","انقلب الوضع","Now the tables have turned.");
I("Through the grapevine","عبر الإشاعات","I heard it through the grapevine.");
I("Tie the knot","يتزوج","They tied the knot in June.");
I("Touch and go","غير مؤكد وخطر","It was touch and go for a while.");
I("Turn over a new leaf","يبدأ صفحة جديدة","He turned over a new leaf.");
I("Twist someone's arm","يضغط عليه ليوافق","You twisted my arm.");
I("Under pressure","تحت ضغط","I work well under pressure.");
I("Up to scratch","بالمستوى المطلوب","The work isn't up to scratch.");
I("Walk on eggshells","يتحرك بحذر شديد","I'm walking on eggshells around him.");
I("Weather the storm","يتجاوز الأزمة","The company weathered the storm.");
I("Wear your heart on your sleeve","يظهر مشاعره بوضوح","He wears his heart on his sleeve.");
I("Word of mouth","الإعلان بالتناقل","We grew through word of mouth.");
I("Worth your salt","كفء في عمله","Any chef worth his salt knows this.");
I("Yours truly","أنا (بتفكه)","Yours truly cooked dinner.");
