// الدفعة 3 — صيغة مختصرة: S(عبارة، معنى، مثال، لهجة) للـ slang و I(...) للـ idioms
const S=(en,ar,ex,reg="US")=>EXPRESSIONS.push({t:"slang",en,ar,ex,tone:"casual",reg});
const I=(en,ar,ex,reg="ALL")=>EXPRESSIONS.push({t:"idiom",en,ar,ex,tone:"neutral",reg});
S("Dope","رائع ومميز","That new song is dope.");
S("Sick","مذهل (بمعنى إيجابي)","Did you see that trick? Sick!");
S("Legit","حقيقي وموثوق","Is this website legit?");
S("Chill","هادئ ومسترخٍ","He's really chill, you'll like him.");
S("Hype","حماس كبير أو ضجة","Everyone's hyped for the new game.");
S("Fam","صديق مقرّب (من family)","What's up, fam?");
S("Yeet","يرمي بقوة","He yeeted the ball over the fence.");
S("Simp","يبالغ في إظهار الاهتمام بشخص يعجبه","Stop simping over her.");
S("Stan","معجب متعصب","I stan this band so hard.");
S("Tea","أخبار ونميمة","Okay, spill the tea!");
S("Shade","كلام يحمل انتقادًا مبطنًا","She threw shade at his outfit.");
S("Drip","أناقة ومظهر لافت","Look at his drip today.");
S("GOAT","الأفضل في كل العصور (Greatest Of All Time)","Messi is the GOAT.");
S("Fire","ممتاز جدًا","Your new track is fire.");
S("Mid","عادي ودون المتوسط","The movie was kind of mid.");
S("Cringe","محرج أو سخيف","That ad is so cringe.");
S("Highkey","بشكل واضح وصريح","I'm highkey obsessed with this show.");
S("Extra","مبالغ في ردود فعله","Don't be so extra, it's just a party.");
S("Basic","تقليدي وعادي بلا تميّز","Pumpkin spice is so basic.");
S("Savage","جريء وبلا رحمة","That reply was savage.");
S("Roast","يسخر منه بمزاح","They roasted him at the party.");
S("Clout","نفوذ وشهرة","He does it all for clout.");
S("Glow-up","تحسّن ملحوظ في المظهر أو الحياة","Her glow-up over the summer was huge.");
S("Rizz","جاذبية وقدرة على إقناع الآخرين عاطفيًا","He's got serious rizz.");
S("Delulu","يعيش في وهم وأحلام غير واقعية","She's delulu if she thinks he'll call.");
S("Ick","شعور مفاجئ بالنفور من شخص","I got the ick when he chewed loudly.");
S("Boujee","يتصنّع الرقي والفخامة","This café is a bit boujee.");
S("Wasted","سكران جدًا","They got totally wasted last night.");
S("Buzzed","متحمّس أو ثمل قليلًا حسب السياق","I'm still buzzed from the concert.");
S("Hit me up","تواصل معي","Hit me up when you're free.");
S("Dip","يغادر بسرعة","Let's dip before it gets crowded.");
S("Bummer","أمر مخيّب للآمال","Your flight got cancelled? What a bummer.");
S("Wicked","رائع جدًا (شائع في بوسطن)","That was a wicked game.");
S("Gnarly","صعب أو مذهل أو سيئ حسب السياق","That wave looked gnarly.");
S("Quid","جنيه إسترليني","It only cost ten quid.","UK");
S("Fit","جذّاب","Her brother is well fit.","UK");
S("Innit","أليس كذلك؟","Cold today, innit?","UK");
S("Brolly","مظلة","Take a brolly, it's raining.","UK");
S("Sorted","تم ترتيب الأمر","Don't worry, it's sorted.","UK");
S("Proper","حقيقي أو شديد","That was a proper good meal.","UK");
S("Gaff","بيت أو شقة","Come round to my gaff.","UK");
S("Lush","رائع وجميل","The cake was lush.","UK");
S("Minging","قذر أو مقزز","The bathroom was minging.","UK");
S("Naff","رديء أو قديم الطراز","That jacket is a bit naff.","UK");
S("Blimey","يا إلهي! (تعجب)","Blimey, that's expensive!","UK");
S("Faff","يضيّع الوقت في أمور تافهة","Stop faffing about and get ready.","UK");
S("Peckish","جائع قليلًا","I'm feeling a bit peckish.","UK");
S("Take the mick","يسخر من شخص","Are you taking the mick?","UK");
S("Banter","مزاح ودّي متبادل","It's just friendly banter.","UK");
I("Add insult to injury","يزيد الطين بلة","He was late, and to add insult to injury, he forgot the tickets.");
I("Barking up the wrong tree","يطارد الشيء الخطأ","If you blame me, you're barking up the wrong tree.");
I("Best of both worlds","يجمع بين ميزتين","Working from home gives me the best of both worlds.");
I("Bite off more than you can chew","يتحمل ما يفوق طاقته","I think I bit off more than I can chew.");
I("By the skin of your teeth","بالكاد ونجا بصعوبة","He passed the test by the skin of his teeth.");
I("Cry over spilled milk","يتحسر على ما فات","It's done, so don't cry over spilled milk.");
I("Curiosity killed the cat","الفضول قد يجلب المتاعب","Stop asking. Curiosity killed the cat.");
I("Don't count your chickens","لا تحسب النتيجة قبل حدوثها","The offer isn't final. Don't count your chickens.");
I("Every cloud has a silver lining","في كل شدة جانب مضيء","Every cloud has a silver lining.");
I("Give someone the cold shoulder","يتجاهله عمدًا","She gave me the cold shoulder all day.");
I("Hang in there","اصبر وتماسك","Hang in there, it'll get better.");
I("Hit the sack","يذهب إلى النوم","I'm exhausted, so I'm going to hit the sack.");
I("In hot water","في ورطة","He's in hot water with his boss.");
I("Jump the gun","يتصرف قبل الأوان","Don't jump the gun, wait for the results.");
I("The last straw","القشة التي قصمت ظهر البعير","His rude comment was the last straw.");
I("Let sleeping dogs lie","اترك الأمور الهادئة كما هي","Don't bring it up. Let sleeping dogs lie.");
I("Miss the boat","تفوته الفرصة","If you wait longer, you'll miss the boat.");
I("On cloud nine","في قمة السعادة","She's on cloud nine after the news.");
I("Out of the blue","فجأة ودون توقع","He called me out of the blue.");
I("Play it by ear","يتصرف حسب الظروف دون خطة","We'll just play it by ear.");
I("Read between the lines","يفهم المعنى الخفي","Read between the lines, he doesn't want to go.");
I("See eye to eye","يتفقان في الرأي","We don't always see eye to eye.");
I("Steal the show","يخطف الأضواء","The little kid stole the show.");
I("The elephant in the room","مشكلة واضحة يتجاهلها الجميع","Money is the elephant in the room.");
I("Throw someone under the bus","يضحّي به لينجو بنفسه","He threw me under the bus.");
I("Tip of the iceberg","جزء صغير من مشكلة أكبر","These errors are just the tip of the iceberg.");
I("Under the radar","بعيدًا عن الأنظار","The company stayed under the radar.");
I("Water under the bridge","أمر مضى وانتهى","Our argument is water under the bridge.");
I("When pigs fly","مستحيل أن يحدث","He'll clean his room when pigs fly.");
I("A dime a dozen","شائع ورخيص","Cheap phones are a dime a dozen.");
I("Actions speak louder than words","الأفعال أصدق من الأقوال","Actions speak louder than words.");
I("Add fuel to the fire","يزيد النار اشتعالًا","Your comment just added fuel to the fire.");
I("All ears","كلي آذان صاغية","Tell me more, I'm all ears.");
I("Apple of my eye","أغلى شخص على قلبي","His daughter is the apple of his eye.");
I("At the drop of a hat","فورًا ودون تردد","She'd travel at the drop of a hat.");
I("Bend over backwards","يبذل أقصى جهد","They bent over backwards to help us.");
I("Blow off steam","يفرّغ غضبه","I go running to blow off steam.");
I("Break a leg","حظ سعيد (يقال قبل العروض)","Break a leg tonight!");
I("Burn bridges","يقطع علاقاته نهائيًا","Don't burn bridges when you quit.");
I("Call the shots","يتخذ القرارات","Who calls the shots here?");
I("Come rain or shine","في كل الأحوال","I'll be there, come rain or shine.");
I("Cut to the chase","ادخل في صلب الموضوع","Let's cut to the chase.");
I("Devil's advocate","يتبنى رأيًا معارضًا لمجرد النقاش","Let me play devil's advocate.");
I("Draw the line","يضع حدًا لا يتجاوزه","I draw the line at lying.");
I("Face the music","يتحمل عواقب أفعاله","He must face the music now.");
