// الدفعة 5 — 50 slang + 50 idioms
S("Nailed it","أنجزها بإتقان","I nailed it in the interview.");
S("Wiped out","منهك تمامًا","I'm wiped out after the trip.");
S("Zonked","منهك وينام فورًا","He was zonked by nine.");
S("Pooped","متعب جدًا","We were all pooped after hiking.");
S("Swamped","غارق في العمل","I'm swamped this week.");
S("Cheesy","مبتذل أو مبالغ في العاطفة","That line is so cheesy.");
S("Corny","سخيف ومكرر","His jokes are corny.");
S("Lame","ممل أو سخيف","The party was lame.");
S("Nerd","شخص مولع بالدراسة أو التقنية","He's a proud tech nerd.");
S("Frenemy","صديق ومنافس في الوقت نفسه","She's my frenemy at work.");
S("Chillax","يهدأ ويرتاح","Just chillax, it's fine.");
S("Bromance","صداقة قوية بين رجلين","Their bromance is adorable.");
S("Man cave","غرفة خاصة للرجل في المنزل","He watches games in his man cave.");
S("Brain fart","نسيان مفاجئ","Sorry, I had a brain fart.");
S("Buzzkill","من يفسد المتعة","Don't be a buzzkill.");
S("Photobomb","يظهر في صورة غيره بشكل مفاجئ","My brother photobombed our picture.");
S("Sketchy","مريب وغير آمن","That area feels sketchy at night.");
S("Shady","مشبوه","He's involved in some shady business.");
S("Janky","رديء ومتهالك","This app is so janky.");
S("Newbie","مبتدئ","I'm a newbie at coding.");
S("Noob","مبتدئ (في الألعاب)","Stop playing like a noob.");
S("Pwned","هُزم بسهولة","You just got pwned.");
S("Clutch","حاسم في اللحظة الصعبة","That shot was clutch.");
S("Swag","أناقة وثقة بالنفس","He's got serious swag.");
S("OG","الأصلي أو الأقدم","He's an OG in the music scene.");
S("Fresh","أنيق وعصري","Those sneakers are fresh.");
S("Mad","كثير جدًا","There was mad traffic today.");
S("Cheddar","مال","He's making that cheddar.");
S("Hunk","رجل وسيم قوي البنية","The actor is a total hunk.");
S("Bangin'","ممتاز","This beat is bangin'.");
S("Knees-up","حفلة صاخبة","We had a knees-up last night.","UK");
S("Chippy","مطعم السمك والبطاطس","Let's grab dinner from the chippy.","UK");
S("Doddle","شيء سهل جدًا","The test was a doddle.","UK");
S("Dosh","مال","I've run out of dosh.","UK");
S("Gaffer","المدير أو المسؤول","The gaffer wants a word.","UK");
S("Grub","طعام","What's for grub?","UK");
S("Jammy","محظوظ جدًا","That jammy goal won the game.","UK");
S("Lad","شاب","He's a good lad.","UK");
S("Muppet","شخص أحمق","Don't be a muppet.","UK");
S("Nowt","لا شيء (شمال إنجلترا)","There's nowt to do here.","UK");
S("Plonker","شخص أحمق","I felt like a right plonker.","UK");
S("Sarnie","شطيرة","I'll make a cheese sarnie.","UK");
S("Scran","طعام","The scran here is great.","UK");
S("Shattered","منهك","I'm absolutely shattered.","UK");
S("Tenner","ورقة عشرة جنيهات","Can you lend me a tenner?","UK");
S("Telly","التلفاز","What's on the telly?","UK");
S("Wellies","أحذية مطرية","Put your wellies on.","UK");
S("Yonks","وقت طويل جدًا","I haven't seen him in yonks.","UK");
S("Rubbish","كلام فارغ أو نفايات","That's complete rubbish.","UK");
I("A piece of the pie","نصيب من الأرباح","Everyone wants a piece of the pie.");
I("At the end of your rope","وصلت إلى حدود الصبر","I'm at the end of my rope.");
I("Back against the wall","في موقف لا مفر منه","With his back against the wall, he agreed.");
I("Ballpark figure","رقم تقريبي","Give me a ballpark figure.");
I("Bigger fish to fry","أمور أهم تشغله","I've got bigger fish to fry.");
I("Black sheep","الفرد المختلف المنبوذ في العائلة","He's the black sheep of the family.");
I("Break the bank","يكلّف مبلغًا كبيرًا","A coffee won't break the bank.");
I("Bring home the bacon","يؤمّن دخل الأسرة","She brings home the bacon.");
I("Butter someone up","يتملقه ليحصل على شيء","He buttered me up before asking.");
I("Can't make heads or tails of it","لا يفهم شيئًا","I can't make heads or tails of this.");
I("Catch someone red-handed","يضبطه متلبسًا","They caught him red-handed.");
I("Chip on your shoulder","يحمل ضغينة","He's got a chip on his shoulder.");
I("Clear the air","يزيل سوء التفاهم","We need to clear the air.");
I("Cold turkey","يتوقف عن عادة فجأة","He quit smoking cold turkey.");
I("Come clean","يعترف بالحقيقة","It's time to come clean.");
I("Cry wolf","يطلق إنذارات كاذبة","Don't cry wolf again.");
I("Cut the mustard","يرقى إلى المستوى المطلوب","He couldn't cut the mustard.");
I("Dead end","طريق مسدود","The investigation hit a dead end.");
I("A drop in the ocean","مبلغ ضئيل أمام الحاجة","His donation was a drop in the ocean.");
I("The eleventh hour","اللحظة الأخيرة","They finished at the eleventh hour.");
I("Take at face value","يصدق الظاهر","Don't take his words at face value.");
I("Fit as a fiddle","في أحسن صحة","Grandpa is fit as a fiddle.");
I("Flash in the pan","نجاح عابر","The band was just a flash in the pan.");
I("Food for thought","فكرة تستحق التأمل","That gives me food for thought.");
I("Get a grip","تمالك نفسك","Get a grip, it's only a test.");
I("Get out of bed on the wrong side","يستيقظ سيئ المزاج","He got out of bed on the wrong side.");
I("Give someone a hand","يساعده","Can you give me a hand?");
I("Go bananas","يفقد عقله حماسًا أو غضبًا","The crowd went bananas.");
I("Go with the flow","يتكيف مع الأحداث","Just go with the flow.");
I("Green with envy","يشعر بالغيرة الشديدة","I was green with envy.");
I("Hit the jackpot","يحقق ربحًا كبيرًا","We hit the jackpot with this house.");
I("Hit the roof","يغضب بشدة","Dad hit the roof when he saw it.");
I("Hold water","يبدو منطقيًا","His excuse doesn't hold water.");
I("In a nutshell","باختصار","In a nutshell, we lost.");
I("In the long run","على المدى البعيد","It will pay off in the long run.");
I("Jump on the bandwagon","يتبع الموضة أو الاتجاه السائد","Everyone jumped on the bandwagon.");
I("Keep it under your hat","احتفظ بالسر","Keep it under your hat for now.");
I("Lose your touch","يفقد مهارته","Has he lost his touch?");
I("To make a long story short","باختصار","To make a long story short, I quit.");
I("Off the hook","نجا من المسؤولية","The manager let him off the hook.");
I("On the ball","منتبه وسريع","She's really on the ball.");
I("On the same page","متفقان في الفهم","Let's make sure we're on the same page.");
I("Once bitten, twice shy","من لُدغ مرة يحذر","Once bitten, twice shy.");
I("Out of the question","مستحيل","A holiday is out of the question.");
I("A penny for your thoughts","بماذا تفكر؟","A penny for your thoughts?");
I("Put your cards on the table","يكشف نواياه بوضوح","Let's put our cards on the table.");
I("Rock the boat","يثير المشاكل","Don't rock the boat now.");
I("Scratch the surface","يلمس الجزء السطحي فقط","We've barely scratched the surface.");
I("Sit tight","ينتظر بصبر","Sit tight, help is coming.");
