// الدفعة 11 — 200 slang + 200 idioms
S("Bruh moment","موقف محرج أو مخيّب","Forgetting my wallet was a bruh moment.");
S("Big brain","ذكي جدًا","That's a big brain move.");
S("Caught in 4K","مضبوط بالدليل الواضح","He got caught in 4K.");
S("Crash out","ينفجر غضبًا","He crashed out after the loss.");
S("Era","مرحلة في الحياة","I'm in my reading era.");
S("Ate","أبدع وأتقن","She ate that performance.");
S("Brat","متمرد ومرح (ثقافة 2024)","It's a brat summer.");
S("Lore","قصة خلفية مثيرة","The lore behind this meme is wild.");
S("Mogging","التفوق في المظهر على غيره","He's mogging everyone.");
S("Mewing","تمرين لشكل الفك","He's mewing for a sharper jaw.");
S("Aura","هالة وحضور","He has so much aura.");
S("Sigma","شخص مستقل وواثق","He thinks he's a sigma.");
S("Based","جريء ومتمسك برأيه","That take is based.");
S("Cope","يتعزى بأعذار","That's just cope.");
S("Seethe","يغلي غضبًا","Keep seething.");
S("Copium","أعذار للتخفيف من الإحباط","He's huffing copium.");
S("Hopium","أمل مبالغ فيه","It's pure hopium.");
S("Doomer","متشائم دائمًا","He's a total doomer.");
S("Zoomer","من جيل Z","My little cousin is a zoomer.");
S("Normie","شخص عادي بلا اهتمامات غريبة","Normies won't get this.");
S("Rage bait","محتوى يستفز الغضب","That post is rage bait.");
S("Clickbait","عنوان مضلل لجذب النقرات","Don't fall for clickbait.");
S("Sponcon","محتوى برعاية","That video is sponcon.");
S("Hot girl summer","صيف الثقة والاستمتاع","It's hot girl summer.");
S("Fan service","محتوى يرضي المعجبين","The scene was pure fan service.");
S("Headcanon","تفسير شخصي للمعجب","In my headcanon he's shy.");
S("OTP","الثنائي المفضل","They're my OTP.");
S("Slow burn","علاقة تتطور ببطء","I love a slow burn romance.");
S("Serving looks","يبدو مذهلًا","She's serving looks.");
S("Yas queen","تشجيع حماسي","Yas queen, you did it!");
S("Hang loose","استرخِ","Just hang loose, man.");
S("Gnar","صعب أو مذهل","Those waves are gnar.");
S("Hurl","يتقيأ","I'm going to hurl.");
S("Toast","منتهٍ أو مهزوم","If he finds out, we're toast.");
S("Fried","منهك ذهنيًا","My brain is fried.");
S("Beat","متعب","I'm beat after work.");
S("Slammed","مشغول جدًا","We're slammed today.");
S("Buried","غارق في العمل","I'm buried in emails.");
S("Choke","يفشل تحت الضغط","He choked in the final.");
S("Whiff","يخطئ الهدف","I whiffed the free throw.");
S("Dud","شيء فاشل","The new phone is a dud.");
S("Fluke","نجاح بالصدفة","It was a total fluke.");
S("Hail Mary","محاولة أخيرة يائسة","It was a Hail Mary pass.");
S("Airball","رمية فاشلة تمامًا","He airballed the shot.");
S("Swish","تسديدة مثالية","Swish! Nothing but net.");
S("Plug","يروّج","Let me plug my new book.");
S("Hang out","يقضي وقتًا مع الأصدقاء","Let's hang out later.");
S("Hit the town","يخرج للسهر","Let's hit the town.");
S("Crash","ينام عند أحدهم","Can I crash at your place?");
S("Chow down","يأكل بشهية","Let's chow down.");
S("Brewskis","كؤوس بيرة","Let's grab some brewskis.");
S("Nosebleed","مقاعد بعيدة مرتفعة","We had nosebleed seats.");
S("Wheels","سيارة","Nice wheels!");
S("Digs","مسكن","Nice digs, man.");
S("Pad","شقة","Come over to my pad.");
S("Threads","ملابس","Cool threads!");
S("Shades","نظارات شمسية","Nice shades.");
S("Bling-bling","مجوهرات لامعة","All that bling-bling is heavy.");
S("Benjamins","أوراق المئة دولار","He's stacking Benjamins.");
S("Grand","ألف دولار","It cost five grand.");
S("Smackers","دولارات","Fifty smackers!");
S("Clams","دولارات","That'll be ten clams.");
S("Paper","مال","He's chasing paper.");
S("Bread","مال","Gotta earn some bread.");
S("Dough","مال","I need some dough.");
S("Coin","مال","He's making coin.");
S("Loot","غنيمة أو مال","Look at all that loot.");
S("Ride shotgun","يجلس بجانب السائق","I'll ride shotgun.");
S("Wingman","صديق يساعدك في التعرف على أحد","He's my wingman.");
S("Player","شخص يغازل كثيرين","He's a player.");
S("Smooth","واثق وجذاب","He's so smooth.");
S("Crush","إعجاب","I have a crush on her.");
S("Hook up with","يتعرف عاطفيًا","He hooked up with her.");
S("Make out","يتبادلان القبل","They were making out.");
S("Rebound","علاقة بعد انفصال","He's just a rebound.");
S("Dump","ينهي علاقة","She dumped him.");
S("Buddy","صديق","Hey, buddy!");
S("Chum","صديق","Old chum of mine.");
S("Amigo","صديق (إسباني)","Hey, amigo!");
S("Compadre","رفيق","He's my compadre.");
S("Sidekick","مساعد","Every hero needs a sidekick.");
S("Banging","رائع جدًا","This tune is banging.","UK");
S("Bantz","مزاح ودي","Just some bantz.","UK");
S("Calm","حسنًا (لندن)","Calm, no problem.","UK");
S("Mandem","مجموعة شباب","I'm out with the mandem.","UK");
S("Roadman","شاب من الشارع","He's a roadman.","UK");
S("Ends","الحي","I'm from the ends.","UK");
S("Bait","واضح أو مكشوف","That's so bait.","UK");
S("Dench","قوي أو ممتاز","That meal was dench.","UK");
S("Wavy","مميز وأنيق","His style is wavy.","UK");
S("Mugged off","تعرض للسخرية","I got mugged off.","UK");
S("Creps","أحذية رياضية","Nice creps!","UK");
S("Garms","ملابس","New garms!","UK");
S("Merk","يهزم بسهولة","We merked them.","UK");
S("Leng","جذاب","She's leng.","UK");
S("Blotto","ثمل تمامًا","He was blotto.","UK");
S("Bevvied","ثمل","We got bevvied.","UK");
S("Hammered","ثمل جدًا","They were hammered.","UK");
S("Mullered","مهزوم أو ثمل","We got mullered.","UK");
S("Sozzled","ثمل","He's sozzled.","UK");
S("Pie-eyed","ثمل جدًا","She was pie-eyed.","UK");
S("Tiddly","ثمل قليلًا","I'm a bit tiddly.","UK");
S("Merry","مرح وثمل قليلًا","She's merry.","UK");
S("Lashed","ثمل","He was lashed.","UK");
S("Paralytic","ثمل لا يقوى على الحركة","He was paralytic.","UK");
S("Battered","ثمل أو مضروب","I got battered last night.","UK");
S("Ginormous","ضخم جدًا","A ginormous cake.","UK");
S("Humongous","هائل","A humongous dog.","UK");
S("Skew-whiff","مائل","The picture's skew-whiff.","UK");
S("Higgledy-piggledy","فوضوي","Books higgledy-piggledy.","UK");
S("Topsy-turvy","مقلوب","Life is topsy-turvy.","UK");
S("Willy-nilly","عشوائيًا","He spends willy-nilly.","UK");
S("Hotchpotch","خليط عشوائي","A hotchpotch of ideas.","UK");
S("Rigmarole","إجراءات معقدة","What a rigmarole!","UK");
S("Palaver","جلبة وتعقيد","What a palaver!","UK");
S("Hullabaloo","ضجة","What's the hullabaloo?","UK");
S("Brouhaha","ضجة وجدال","A brouhaha erupted.","UK");
S("Shindig","حفلة كبيرة","A big shindig.","UK");
S("Bash","حفلة","Birthday bash tonight!","UK");
S("Do","حفلة","We had a do.","UK");
S("Tickled pink","سعيد جدًا","I'm tickled pink.","UK");
S("Natter","يتحدث بودّ","We nattered for hours.","UK");
S("Witter","يثرثر","Stop wittering on.","UK");
S("Waffle","يثرثر بلا فائدة","Stop waffling.","UK");
S("Rabbit on","يثرثر","He rabbits on forever.","UK");
S("Dither","يتردد","Don't dither.","UK");
S("Pootle","يتجول ببطء","I pootled around town.","UK");
S("Potter","يتسكع بلا هدف","I potter in the garden.","UK");
S("Dawdle","يتباطأ","Don't dawdle!","UK");
S("Pop your clogs","يموت (مازحًا)","He popped his clogs.","UK");
S("Snaffle","يأخذ بسرعة","Who snaffled my biscuit?","UK");
S("Done in","منهك","I'm done in.","UK");
S("Hyper","نشيط جدًا","The kids are hyper.");
S("Wired","متحمس ومتوتر","I'm wired on coffee.");
S("Jittery","عصبي","I feel jittery.");
S("Antsy","قلق","He's antsy.");
S("Jumpy","سريع الانفعال","I'm jumpy tonight.");
S("Uptight","متوتر","Don't be so uptight.");
S("Chill pill","هدّئ نفسك","Take a chill pill.");
S("Wuss","جبان","Don't be a wuss.");
S("Scaredy-cat","جبان","Don't be a scaredy-cat.");
S("Goody-goody","مثالي بتصنّع","She's a goody-goody.");
S("Teacher's pet","المفضل لدى المعلم","He's the teacher's pet.");
S("Brown-noser","متملق","He's a brown-noser.");
S("Suck-up","متملق","Don't be a suck-up.");
S("Kiss-up","متملق","He's a kiss-up.");
S("Yes-man","من يوافق دائمًا","He's a yes-man.");
S("Doormat","شخص يُداس عليه","Don't be a doormat.");
S("Pushover","سهل الإقناع","He's a pushover.");
S("Softie","رقيق القلب","He's a softie.");
S("Tough cookie","شخص قوي","She's a tough cookie.");
S("Smart cookie","شخص ذكي","She's a smart cookie.");
S("Cool cat","شخص رائع","He's a cool cat.");
S("Big shot","شخص مهم","He thinks he's a big shot.");
S("Hotshot","شخص بارع ومغرور","A young hotshot lawyer.");
S("Whiz kid","طفل عبقري","He's a whiz kid.");
S("Prodigy","موهوب","She's a piano prodigy.");
S("Geek","مهووس","I'm a computer geek.");
S("Dork","شخص أخرق","He's a lovable dork.");
S("Loser","خاسر","Don't call him a loser.");
S("Wimp","ضعيف","He's a wimp.");
S("Jerk","شخص فظ","He's a jerk.");
S("Weirdo","شخص غريب","He's a weirdo.");
S("Oddball","غريب الأطوار","He's an oddball.");
S("Crackpot","غريب الأفكار","He's a crackpot.");
S("Kook","غريب","She's a kook.");
S("Nutcase","مجنون","He's a nutcase.");
S("Screwball","غريب","What a screwball!");
S("Airhead","قليل الفهم","Don't be an airhead.");
S("Ditz","شخص مشتت","She's a ditz.");
S("Dimwit","قليل الذكاء","What a dimwit!");
S("Dunce","غبي","Don't be a dunce.");
S("Bigmouth","ثرثار","He's a bigmouth.");
S("Blabbermouth","ثرثار لا يكتم سرًا","Don't tell that blabbermouth.");
S("Motormouth","كثير الكلام","He's a motormouth.");
S("Busybody","فضولي","She's a busybody.");
S("Snoop","يتجسس","Stop snooping.");
S("Peeping Tom","متلصص","He's a peeping Tom.");
S("Rat","يشي بأصدقائه","He ratted on us.");
S("Squeal","يشي","He squealed.");
S("Gyatt","تعبير مبالغ عن الإعجاب بالجسم","Gyatt, look at that car!");
S("Fanum tax","أخذ جزء من طعام صديق مازحًا","Fanum tax on your fries.");
S("Skibidi","كلمة بلا معنى محدد (ميم)","He keeps saying skibidi.");
S("Only in Ohio","يحدث أشياء غريبة فقط هنا (ميم)","A goat on the roof? Only in Ohio.");
S("NGL","لن أكذب","NGL, I liked it.");
S("SMH","هزّ الرأس استنكارًا","SMH, he did it again.");
S("FR","بصدق (for real)","FR, that's true.");
S("ONG","أقسم بالله (on god)","ONG, I saw it.");
S("IMO","في رأيي","IMO, it's overrated.");
S("IKR","أعرف! (I know, right)","Ugh, Mondays. IKR?");
S("TMI","معلومات شخصية أكثر من اللازم","TMI, I didn't need to know.");
S("BRB","سأعود حالًا","BRB, grabbing a snack.");
S("TFW","ذلك الشعور عندما","TFW the weekend arrives.");
S("FTW","من أجل الفوز","Pizza FTW!");
S("AF","جدًا (as f***)","I'm tired af.");
S("RN","الآن (right now)","I'm busy rn.");
S("Tho","لكن","It's good tho.");
S("LOL","أضحك بصوت عالٍ","LOL, that's hilarious.");
S("LMAO","أموت من الضحك","LMAO, he fell!");
S("ROFL","أتدحرج من الضحك","ROFL, so funny.");
I("Lay down the law","يفرض قواعد صارمة","The coach laid down the law.");
I("Learn the hard way","يتعلم بتجربة مؤلمة","I learned it the hard way.");
I("Leave in the dust","يتفوق بفارق كبير","She left them in the dust.");
I("Let the chips fall where they may","يقبل النتائج مهما كانت","Do the right thing and let the chips fall.");
I("Level with someone","يصارحه","I'll level with you.");
I("Lip service","كلام بلا فعل","He paid lip service to reform.");
I("Live it up","يستمتع بالحياة","We lived it up in Paris.");
I("A load off your mind","راحة بعد قلق","Finishing was a load off my mind.");
I("Lock, stock and barrel","كل شيء بالكامل","He sold the business lock, stock and barrel.");
I("Long in the tooth","كبير في السن","He's a bit long in the tooth.");
I("Loose cannon","شخص متهور لا يمكن التنبؤ به","He's a loose cannon.");
I("Low-hanging fruit","أسهل الأهداف","Start with the low-hanging fruit.");
I("Make hay while the sun shines","اغتنم الفرصة","Make hay while the sun shines.");
I("Make light of","يستخف","Don't make light of it.");
I("Make or break","حاسم للنجاح أو الفشل","This is make or break.");
I("Make your mark","يترك بصمته","She made her mark early.");
I("Meet halfway","يتنازل للوسط","Let's meet halfway.");
I("Method to the madness","منطق خلف الفوضى","There's a method to his madness.");
I("Mum's the word","التزم الصمت","Mum's the word about the gift.");
I("Music to my ears","كلام يسعدني","That's music to my ears.");
I("Name drop","يذكر أسماء مشاهير ليتفاخر","He name-dropped all night.");
I("Neck of the woods","منطقة أو حي","What brings you to my neck of the woods?");
I("Needless to say","لا داعي للقول","Needless to say, I was upset.");
I("New kid on the block","القادم الجديد","He's the new kid on the block.");
I("Nine-to-five","وظيفة اعتيادية","I'm tired of my nine-to-five.");
I("No-brainer","قرار سهل جدًا","Taking the deal is a no-brainer.");
I("No dice","لا نتيجة","I asked, but no dice.");
I("No holds barred","بلا قيود","It was a no holds barred debate.");
I("Not a chance","مستحيل","Me, skydive? Not a chance.");
I("Nothing to sneeze at","ليس قليلًا","A raise is nothing to sneeze at.");
I("Null and void","باطل","The contract is null and void.");
I("Off base","مخطئ","You're way off base.");
I("Off the charts","فائق القياس","The demand is off the charts.");
I("Off the wall","غريب وغير تقليدي","His ideas are off the wall.");
I("Old habits die hard","العادات القديمة تصعب إزالتها","Old habits die hard.");
I("On the dot","في الموعد تمامًا","He arrived at nine on the dot.");
I("On the line","على المحك","My job is on the line.");
I("One for the road","كأس أخير قبل المغادرة","Just one for the road.");
I("One-man show","شخص يفعل كل شيء","The company is a one-man show.");
I("Out of hand","خارج السيطرة","The party got out of hand.");
I("Out of left field","غير متوقع","The question came out of left field.");
I("Over the hill","كبر في السن","Don't call me over the hill.");
I("Own worst enemy","عدو نفسه","He's his own worst enemy.");
I("Packed like sardines","مزدحم جدًا","We were packed like sardines.");
I("Par for the course","أمر معتاد","Delays are par for the course.");
I("Pay the piper","يتحمل العواقب","Now it's time to pay the piper.");
I("Pay your dues","يكسب مكانته بالجهد","You have to pay your dues.");
I("Pick up the pieces","يرمم ما تحطم","She picked up the pieces.");
I("Pin your hopes on","يعلق آماله","He pinned his hopes on it.");
I("Play hardball","يتشدد في المفاوضة","They played hardball.");
I("Play second fiddle","يأتي في المرتبة الثانية","I won't play second fiddle.");
I("Plenty of fish in the sea","فرص كثيرة غيرها","Move on, there's plenty of fish in the sea.");
I("Point of no return","نقطة اللاعودة","We've passed the point of no return.");
I("Pull the plug","يوقف الأمر","They pulled the plug on the project.");
I("Pull the rug out from under","يفاجئه بسحب الدعم","They pulled the rug out from under us.");
I("Put a lid on it","اصمت","Put a lid on it, I'm busy.");
I("Put your finger on","يحدد بدقة","I can't put my finger on it.");
I("Quiet as a mouse","هادئ جدًا","He was quiet as a mouse.");
I("Raise eyebrows","يثير الدهشة","The decision raised eyebrows.");
I("Read the room","يفهم مزاج الحاضرين","Learn to read the room.");
I("Red herring","تضليل","That clue was a red herring.");
I("Red tape","بيروقراطية","Too much red tape.");
I("Ride out the storm","يصمد حتى تنتهي الأزمة","We'll ride out the storm.");
I("Right off the bat","من البداية","He told me right off the bat.");
I("Ring true","يبدو صادقًا","Her story rings true.");
I("Rob Peter to pay Paul","يسدد دينًا بدين آخر","It's robbing Peter to pay Paul.");
I("Rock bottom","أدنى مستوى","Prices hit rock bottom.");
I("Rub salt in the wound","يزيد الألم","Don't rub salt in the wound.");
I("Rub someone the wrong way","يزعجه","He rubs me the wrong way.");
I("Run a tight ship","يدير بصرامة","She runs a tight ship.");
I("Run in the family","موروث في العائلة","Music runs in the family.");
I("Run the gauntlet","يواجه الصعوبات","Reporters ran the gauntlet.");
I("Sail through","ينجح بسهولة","She sailed through the exam.");
I("Salt of the earth","شخص طيب وبسيط","He's the salt of the earth.");
I("Sell like hotcakes","يباع بسرعة","The tickets sold like hotcakes.");
I("Set the stage","يمهد","This sets the stage for talks.");
I("Shake a leg","أسرع","Shake a leg, we're late!");
I("Shape up or ship out","حسّن أداءك أو ارحل","Shape up or ship out.");
I("The ship has sailed","فات الأوان","That ship has sailed.");
I("Shoot yourself in the foot","يضر نفسه","He shot himself in the foot.");
I("Shot in the dark","تخمين عشوائي","It was a shot in the dark.");
I("Sit on the fence","يتردد في الاختيار","Stop sitting on the fence.");
I("Skeleton in the closet","سر مخزٍ","Everyone has a skeleton in the closet.");
I("Skin and bones","نحيف جدًا","He's skin and bones.");
I("Slap on the wrist","عقوبة خفيفة","He got a slap on the wrist.");
I("Slippery slope","منحدر خطير","It's a slippery slope.");
I("Small fry","شخص غير مهم","They only caught small fry.");
I("Smooth sailing","سير سهل","It's smooth sailing from here.");
I("Snowball effect","تأثير متصاعد","It had a snowball effect.");
I("Soft spot","ضعف عاطفي","I have a soft spot for him.");
I("Spread yourself thin","يشتت جهده","Don't spread yourself too thin.");
I("Stand your ground","يثبت على موقفه","She stood her ground.");
I("Steal someone's thunder","يسرق الأضواء","He stole my thunder.");
I("Stick out like a sore thumb","بارز بشكل واضح","He stuck out like a sore thumb.");
I("Stir the pot","يثير الفتنة","He loves to stir the pot.");
I("A stone's throw","مسافة قريبة جدًا","It's a stone's throw from here.");
I("Straight and narrow","الطريق القويم","He stayed on the straight and narrow.");
I("Sweat blood","يبذل جهدًا شاقًا","I sweated blood over it.");
I("Sweep under the rug","يخفي المشكلة","They swept it under the rug.");
I("Swim against the tide","يعاكس التيار","She swam against the tide.");
I("Take a back seat","يتراجع","He took a back seat.");
I("Take a stand","يتخذ موقفًا","It's time to take a stand.");
I("Take it on the chin","يتحمل بشجاعة","He took the loss on the chin.");
I("Take the edge off","يخفف الحدة","Tea takes the edge off.");
I("Take the fall","يتحمل اللوم","He took the fall for them.");
I("Take the wind out of someone's sails","يحبط حماسه","The news took the wind out of my sails.");
I("Talk shop","يتحدث عن العمل","Let's not talk shop.");
I("Talk the talk","يتكلم بثقة","He can talk the talk.");
I("Tell tales","يشي","Don't tell tales.");
I("That's a wrap","انتهى","That's a wrap, folks.");
I("The writing on the wall","علامات واضحة للنهاية","I saw the writing on the wall.");
I("Thick skin","قدرة على تحمل النقد","You need thick skin.");
I("Think outside the box","يفكر بشكل مبتكر","Think outside the box.");
I("Third time's the charm","المرة الثالثة تنجح","Third time's the charm.");
I("Throw caution to the wind","يتخلى عن الحذر","She threw caution to the wind.");
I("Tighten your belt","يقتصد","We must tighten our belts.");
I("Toe the line","يلتزم بالقواعد","He toes the line.");
I("Top of the heap","في القمة","They're top of the heap.");
I("Touch a nerve","يمس موضعًا حساسًا","That touched a nerve.");
I("Tough love","قسوة بدافع المحبة","It's tough love.");
I("Trial and error","التجربة والخطأ","I learned by trial and error.");
I("Tricks of the trade","أسرار المهنة","He knows the tricks of the trade.");
I("Turn the tables","يقلب الوضع","She turned the tables.");
I("A twist of fate","تقلب القدر","A twist of fate saved him.");
I("Under lock and key","محفوظ بإحكام","Keep it under lock and key.");
I("Under the thumb","تحت السيطرة","She keeps him under her thumb.");
I("Up and running","يعمل","The site is up and running.");
I("Up for grabs","متاح للجميع","Two spots are up for grabs.");
I("Up the ante","يرفع الرهان","They upped the ante.");
I("Upper crust","الطبقة الراقية","He's from the upper crust.");
I("Walk the walk","يطبق ما يقوله","He walks the walk.");
I("Wash your hands of","يتبرأ من","I wash my hands of it.");
I("Watch your back","احذر","Watch your back.");
I("Wear and tear","اهتراء","Normal wear and tear.");
I("Wet blanket","من يفسد المرح","Don't be a wet blanket.");
I("Whet your appetite","يثير الشهية أو الاهتمام","The trailer whet my appetite.");
I("White elephant","شيء مكلف عديم الفائدة","The stadium is a white elephant.");
I("Wild card","عنصر غير متوقع","He's the wild card.");
I("Win-win","مربح للطرفين","It's a win-win.");
I("On a wing and a prayer","بأمل ضعيف","We did it on a wing and a prayer.");
I("Wolf in sheep's clothing","ذئب في ثوب حمل","He's a wolf in sheep's clothing.");
I("Word for word","حرفيًا","He repeated it word for word.");
I("Work like a dog","يعمل بجهد","I worked like a dog.");
I("Worth a shot","يستحق المحاولة","It's worth a shot.");
I("Zero in on","يركز على","Zero in on the problem.");
I("Mad as a hatter","مجنون تمامًا","He's mad as a hatter.","UK");
I("Mad as a March hare","مجنون","She's mad as a March hare.","UK");
I("Throw a spanner in the works","يعرقل الخطة","He threw a spanner in the works.","UK");
I("Keep your pecker up","ابق متفائلًا","Keep your pecker up.","UK");
I("Not for all the tea in China","مستحيل","Not for all the tea in China.");
I("Cock a snook","يسخر باستهزاء","He cocked a snook at the rules.","UK");
I("Barking mad","مجنون","He's barking mad.","UK");
I("Bang to rights","متلبس بالجرم","They caught him bang to rights.","UK");
I("The bee's knees","الأفضل","This café is the bee's knees.");
I("The cat's pyjamas","الأفضل","Your new car is the cat's pyjamas.");
I("Pull a face","يعبّس","Don't pull a face.","UK");
I("Pull your socks up","حسّن أداءك","Pull your socks up.","UK");
I("Take the biscuit","يتجاوز الحدود","That takes the biscuit.","UK");
I("Up the creek","في ورطة","We're up the creek.");
I("Dutch courage","شجاعة من الكحول","He needed Dutch courage.");
I("French leave","مغادرة بلا إذن","He took French leave.","UK");
I("Look a gift horse in the mouth","ينتقد الهدية","Don't look a gift horse in the mouth.");
I("Nest egg","مدخرات","They saved a nest egg.");
I("Pig in a poke","شراء دون معاينة","Don't buy a pig in a poke.");
I("Sour grapes","غيرة من النجاح","It's just sour grapes.");
I("Have a bone to pick","لديه عتاب","I have a bone to pick with you.");
I("Have a screw loose","فاقد لعقله","He's got a screw loose.");
I("Heart-to-heart","حديث صريح","We had a heart-to-heart.");
I("Hit the ceiling","يغضب بشدة","Dad hit the ceiling.");
I("Home in on","يركز على","Home in on the details.");
I("In a rut","في روتين ممل","I'm stuck in a rut.");
I("In the doghouse","في موقف سيئ","He's in the doghouse.");
I("In the limelight","تحت الأضواء","She loves the limelight.");
I("In the lap of the gods","بيد القدر","It's in the lap of the gods.");
I("Jump for joy","يقفز فرحًا","I jumped for joy.");
I("Keep up with the Joneses","يجاري جيرانه","Stop keeping up with the Joneses.");
I("Kick up your heels","يستمتع","Kick up your heels tonight.");
I("Kiss and tell","يفشي أسرار علاقته","She won't kiss and tell.");
I("Lead someone on","يخدعه عاطفيًا","He led her on.");
I("A leap of faith","ثقة دون دليل","It was a leap of faith.");
I("Let the dust settle","ينتظر هدوء الأمور","Let the dust settle.");
I("Lick your wounds","يتعافى من الهزيمة","He's licking his wounds.");
I("Make your blood boil","يغضبك","It makes my blood boil.");
I("Nitty-gritty","التفاصيل الجوهرية","Let's get to the nitty-gritty.");
I("Odd one out","الغريب بينهم","I'm the odd one out.");
I("Once in a lifetime","مرة في العمر","It's a once in a lifetime offer.");
I("Over my dead body","لن يحدث أبدًا","Over my dead body!");
I("Pull out all the stops","يبذل أقصى جهد","They pulled out all the stops.");
I("Put on a brave face","يتظاهر بالشجاعة","She put on a brave face.");
I("Put two and two together","يستنتج","I put two and two together.");
I("Quick on the draw","سريع البديهة","She's quick on the draw.");
I("Rest on your laurels","يكتفي بنجاحاته","Don't rest on your laurels.");
I("See red","يغضب","I saw red.");
I("Set your sights on","يضع هدفًا","She set her sights on a PhD.");
I("Stick your neck out","يخاطر من أجل غيره","I stuck my neck out for him.");
I("Turn a deaf ear","يتجاهل","He turned a deaf ear.");
I("A wake-up call","تنبيه صادم","It was a wake-up call.");
I("Water off a duck's back","لا يتأثر","Criticism is water off a duck's back.");
I("Wipe the slate clean","يبدأ من جديد","Let's wipe the slate clean.");
I("Zip your lip","اسكت","Zip your lip!");
