// الدفعة 10 — 200 slang + 200 idioms
S("Amazeballs","مذهل جدًا","The cake was amazeballs.");
S("Awesomesauce","رائع جدًا","This game is awesomesauce.");
S("Beef","خلاف أو عداوة","They've had beef since high school.");
S("Blast","وقت ممتع جدًا","We had a blast at the park.");
S("Bogart","يستأثر بالشيء لنفسه","Don't bogart the popcorn.");
S("Brainiac","شخص عبقري","Our class brainiac got full marks.");
S("Buff","مفتول العضلات","He got buff over the summer.");
S("Chug","يشرب دفعة واحدة","He chugged the whole bottle.");
S("Cuffing season","موسم البحث عن علاقة في الشتاء","It's cuffing season again.");
S("Dialed in","مركّز ومتقن لعمله","The team is totally dialed in.");
S("Dime","شخص جذاب جدًا","She's a total dime.");
S("Doxx","ينشر معلومات شخص الخاصة","They doxxed him online.");
S("Down bad","يائس عاطفيًا","He's down bad for her.");
S("Earworm","أغنية تعلق في الرأس","That chorus is an earworm.");
S("Elite","ممتاز جدًا","That play was elite.");
S("Finna","على وشك (fixing to)","I'm finna head out.");
S("Fugly","قبيح جدًا","Those shoes are fugly.");
S("Goated","الأفضل على الإطلاق","He's goated at chess.");
S("Gym bro","شاب مهووس بالنادي","Every gym bro drinks protein shakes.");
S("Heater","ضربة أو أداء ممتاز","That song is a heater.");
S("Icy","بارد الطباع أو مرصّع بالمجوهرات","Her stare was icy.");
S("Jawn","شيء أو شخص (فيلادلفيا)","Pass me that jawn.");
S("Kickin' it","يسترخي مع الأصدقاء","We were just kickin' it.");
S("Mooch","يعيش على حساب غيره","He mooches off his friends.");
S("Nah","لا","Nah, I'm good.");
S("Obvi","بالطبع (obviously)","Obvi I'm coming!");
S("On fleek","في أبهى صورة","Her eyebrows are on fleek.");
S("Ope","تعبير عن الاعتذار المفاجئ","Ope, sorry, let me squeeze by.");
S("Opp","خصم أو عدو","Watch out for the opps.");
S("Out of pocket","متجاوز للحدود","That comment was out of pocket.");
S("Periodt","وانتهى النقاش","I'm right, periodt.");
S("Pull up","يحضر أو يصل","Pull up at nine.");
S("Slide into DMs","يراسل شخصًا برسائل خاصة","He slid into her DMs.");
S("Sweaty","شديد الجدية في اللعب","Ranked games get so sweaty.");
S("Thicc","ممتلئ الجسم بجاذبية","She's looking thicc.");
S("Tilted","منفعل ومشتت","I'm tilted after that loss.");
S("Tweaking","يتصرف بغرابة","You're tweaking if you believe that.");
S("Twinning","يرتدي مثل غيره","We're twinning today.");
S("Understood the assignment","أدى المطلوب بإتقان","She understood the assignment.");
S("Wig","مذهل (يطيّر العقل)","That performance? Wig!");
S("Bussin","لذيذ جدًا","The tacos were bussin.");
S("Cheat code","طريقة مختصرة للنجاح","Sleep is a cheat code.");
S("Chonk","ممتلئ ولطيف","Look at that chonk of a cat.");
S("Clown","يتصرف بحماقة","Don't clown around.");
S("Cooking","يؤدي ببراعة","Let him cook.");
S("Dead inside","فاقد الشعور","Monday mornings leave me dead inside.");
S("Gatekeep","يحتكر الوصول","Don't gatekeep that recipe.");
S("Glaze","يمدح بإفراط","Stop glazing him.");
S("Grindset","عقلية العمل الدؤوب","He's on that grindset.");
S("Hits the spot","يشبع الرغبة تمامًا","This soup hits the spot.");
S("Humblebrag","تفاخر مغلف بالتواضع","That's just a humblebrag.");
S("Kiddo","طفل (بلطف)","Hey, kiddo!");
S("L","خسارة","Taking that L today.");
S("Nepo baby","ابن أو ابنة مشاهير يستفيد من اسمه","She's a nepo baby.");
S("Ratchet","فوضوي أو رديء","That party got ratchet.");
S("Sauce","أناقة وجاذبية","He's got sauce.");
S("Stress eat","يأكل بسبب التوتر","I stress eat at night.");
S("Sus af","مشبوه جدًا","That link is sus af.");
S("Swerve","يتجنب","I swerved that meeting.");
S("Take an L","يخسر","He took an L today.");
S("Throw hands","يتعارك","They almost threw hands.");
S("Touch grass","اخرج للعالم الحقيقي","Go touch grass.");
S("Triggered","منزعج بسهولة","He gets triggered easily.");
S("Tuff","قوي ومثير للإعجاب","That's tuff.");
S("Turn up","يحتفل بحماس","Let's turn up tonight.");
S("Unalive","يموت (تجنبًا للرقابة)","Content creators say unalive.");
S("Vibe killer","من يفسد الأجواء","He's a vibe killer.");
S("Wack","سيئ","That joke was wack.");
S("Whip","سيارة","Check out my new whip.");
S("Wifey","الزوجة أو الحبيبة","That's my wifey.");
S("Yap","يثرثر","He yaps all day.");
S("Yoink","يخطف","Yoink! That's mine now.");
S("Zero chill","عديم الهدوء","She has zero chill.");
S("Zesty","مرح ومتحمس","He's pretty zesty.");
S("Zip it","اصمت","Zip it, I'm watching this.");
S("Zoomies","نوبات نشاط مفاجئة","The puppy has the zoomies.");
S("Bangers","نقانق","Bangers and mash for dinner.","UK");
S("Bender","جلسة شرب طويلة","He went on a bender.","UK");
S("Bird","فتاة (عامي)","He's got a new bird.","UK");
S("Bloomin'","لعين (تخفيف)","It's bloomin' cold.","UK");
S("Boozer","حانة","Meet at the boozer.","UK");
S("Brassic","مفلس","I'm totally brassic.","UK");
S("Buzzin'","متحمس جدًا","I'm buzzin' for the weekend.","UK");
S("Dead on","دقيق أو ممتاز","You're dead on.","UK");
S("Faffing","يضيع الوقت","Stop faffing around.","UK");
S("Grub's up","الطعام جاهز","Grub's up, everyone!","UK");
S("Having a laugh","يمزح أو يسخر","You're having a laugh!","UK");
S("Jog on","ارحل","Jog on, mate.","UK");
S("Kip down","ينام","I'll kip down here.","UK");
S("Mardy bum","شخص متجهم","Stop being a mardy bum.","UK");
S("Mingin'","مقزز","That's mingin'.","UK");
S("Moaning Minnie","شخص دائم التذمر","Don't be a moaning Minnie.","UK");
S("Muppet face","شخص أحمق","You muppet face!","UK");
S("Nesh","يتأثر بالبرد","I'm nesh in winter.","UK");
S("Offie","محل بيع الخمور","I'm off to the offie.","UK");
S("Peg it","يركض بسرعة","Peg it, we're late!","UK");
S("Skive off","يتغيب","Don't skive off.","UK");
S("Slag off","ينتقد بقسوة","Don't slag him off.","UK");
S("Smashing","رائع","That's smashing!","UK");
S("Squid","جنيه","That's five squid.","UK");
S("Taking the biscuit","يتجاوز الحدود","That's taking the biscuit.","UK");
S("Tea leaf","لص","He's a tea leaf.","UK");
S("Whinger","متذمر دائم","He's a whinger.","UK");
S("Bamf","شخص قوي ومخيف ومثير للإعجاب","She's a total bamf.");
S("Big yikes","موقف محرج جدًا","That tweet? Big yikes.");
S("Bougie","يتصنع الرقي","This brunch spot is so bougie.");
S("Brain rot","محتوى تافه يستنزف العقل","Endless shorts are pure brain rot.");
S("Bro code","قواعد الصداقة بين الشباب","That's against the bro code.");
S("Chronically online","غارق في الإنترنت","He's chronically online.");
S("Comfort show","مسلسل مريح يعاد مشاهدته","This is my comfort show.");
S("Dead serious","جاد تمامًا","I'm dead serious.");
S("Dramatic","مبالغ في ردود فعله","Don't be so dramatic.");
S("Face card","وجه جذاب","His face card never declines.");
S("Fake deep","يتظاهر بالعمق","That quote is fake deep.");
S("Fit check","عرض إطلالة اليوم","Fit check before we leave.");
S("Flex on","يتباهى أمام غيره","He flexed on everyone.");
S("Gen Z","جيل الألفية الثانية","Gen Z loves short videos.");
S("Girl dinner","وجبة خفيفة عشوائية","Cheese and crackers: girl dinner.");
S("Glow","يبدو متألقًا","You're glowing today.");
S("Hard launch","إعلان علني عن علاقة","They hard launched on Instagram.");
S("It's giving","يوحي بأجواء معينة","It's giving old money.");
S("Left on read","قرأ الرسالة ولم يرد","She left me on read.");
S("Link up","يلتقي","Let's link up later.");
S("Main quest","الهدف الأساسي","Back to the main quest.");
S("Manifest","يتمنى بقوة ليتحقق","I'm manifesting a promotion.");
S("Menty b","انهيار نفسي ممازح","Having a menty b.");
S("Mid-tier","متوسط المستوى","That restaurant is mid-tier.");
S("No worries","لا تقلق","Sorry! No worries.");
S("Not it","ليس أنا (من يقوم بالمهمة)","Not it! You take out the trash.");
S("Ok boomer","رد ساخر على جيل أكبر","He just said ok boomer.");
S("Ride","سيارة أو رحلة","Need a ride?");
S("Roman Empire","شيء يفكر فيه كثيرًا","This is my Roman Empire.");
S("Sleeper hit","نجاح مفاجئ","The film was a sleeper hit.");
S("Soft launch","تلميح خفي بعلاقة","He soft launched with a photo.");
S("Soft life","حياة مريحة","She's living the soft life.");
S("Stay winning","استمر بالنجاح","Stay winning!");
S("Third wheel","زائد عن الحاجة بين اثنين","I felt like a third wheel.");
S("Touch base","يتواصل","Let's touch base tomorrow.");
S("Vibe shift","تغير في الأجواء","There's a vibe shift this year.");
S("Whatever","لا يهم","Whatever, do what you want.");
S("Wholesome","لطيف ومفرح","That video is so wholesome.");
S("Yassify","يجمّل بشدة","They yassified the photo.");
S("You do you","افعل ما يناسبك","Wear it. You do you.");
S("Zoom fatigue","إرهاق الاجتماعات المرئية","I have Zoom fatigue.");
S("Blagging it","يدّعي المعرفة","I'm just blagging it.","UK");
S("Ding-dong","شجار أو جلبة","We had a ding-dong.","UK");
S("Gammon","شخص متشدد سياسيًا","He's a proper gammon.","UK");
S("Hench","قوي البنية","He's looking hench.","UK");
S("Safe","رائع","Safe, thanks!","UK");
S("Wagwan","ما الأخبار؟","Wagwan, bruv?","UK");
S("Wasteman","شخص عديم الفائدة","Don't be a wasteman.","UK");
S("Allow it","اتركه","Allow it, mate.","UK");
S("Long","ممل ومرهق","That queue is long.","UK");
S("Gassed up","متحمس","I'm gassed up for tonight.","UK");
S("Peng","جذاب أو لذيذ","That food was peng.","UK");
S("Ghosting","قطع التواصل المفاجئ","Ghosting is rude.");
S("Bestie goals","علاقة صداقة مثالية","You two are bestie goals.");
S("Eye roll","تدوير العينين استهزاءً","I gave him an eye roll.");
S("Fangirling","التصرف كمعجبة متحمسة","Stop fangirling over him.");
S("Flake out","يلغي في اللحظة الأخيرة","He flaked out again.");
S("Frenemies","أصدقاء أعداء","We're frenemies.");
S("Go-getter","شخص طموح","She's a real go-getter.");
S("Hype man","من يشجع غيره بحماس","He's my hype man.");
S("Jump scare","فزع مفاجئ في فيلم","That jump scare got me.");
S("Know-it-all","من يدّعي معرفة كل شيء","Nobody likes a know-it-all.");
S("Lightweight","قليل التحمل للشرب","He's a lightweight.");
S("Mean girl","فتاة متنمرة","She's such a mean girl.");
S("No biggie","ليس مهمًا","Sorry I'm late. No biggie.");
S("Overthink","يفرط في التفكير","Stop overthinking it.");
S("Party pooper","من يفسد الحفلة","Don't be a party pooper.");
S("Pro tip","نصيحة مفيدة","Pro tip: book early.");
S("Rando alert","ظهور شخص غريب","Rando alert in the chat.");
S("Screenshot","يلتقط صورة للشاشة","I screenshotted the chat.");
S("Smarty pants","شخص يتظاهر بالذكاء","Okay, smarty pants.");
S("Spoiler alert","تحذير من كشف الأحداث","Spoiler alert: he dies.");
S("Streamer","من يبث مباشرة","He's a gaming streamer.");
S("Sugar daddy","رجل ثري ينفق على شابة","The film features a sugar daddy.");
S("Takeout","طعام جاهز للأخذ","Let's order takeout.");
S("Throwing shade","ينتقد بشكل غير مباشر","She's throwing shade again.");
S("Tryhard","يبالغ في المحاولة","He's such a tryhard.");
S("Unfriend","يلغي الصداقة","I unfriended him.");
S("Up for it","مستعد","Are you up for it?");
S("Wing it","يرتجل","I'll just wing it.");
S("Workaholic","مدمن عمل","He's a workaholic.");
S("Yolo","تعيش مرة واحدة فقط","Yolo, let's go!");
S("Zing","رد لاذع","What a zing!");
S("Bits","أجزاء متفرقة","Pick up the bits.","UK");
S("Cheeky pint","كأس بيرة سريع","Fancy a cheeky pint?","UK");
S("Chin-wag","حديث ودي","Let's have a chin-wag.","UK");
S("Cream crackered","منهك","I'm cream crackered.","UK");
S("Easy peasy","سهل جدًا","It's easy peasy.","UK");
S("Fancy","يرغب أو معجب","Do you fancy her?","UK");
S("Gutted for you","آسف لأجلك","I'm gutted for you.","UK");
S("Hobnob","يختلط بالمشاهير","He hobnobs with MPs.","UK");
S("Jammy dodger","محظوظ جدًا","You jammy dodger!","UK");
S("Knees up","حفلة صاخبة","We had a knees up.","UK");
S("Make a bomb","يربح الكثير","He made a bomb.","UK");
S("Naff off","اغرب عن وجهي","Naff off!","UK");
S("Not on","غير مقبول","That's not on.","UK");
S("Shufti","نظرة سريعة","Have a shufti.","UK");
I("A chip off the old block","يشبه أباه","He's a chip off the old block.");
I("A cut above","أفضل من غيره","This hotel is a cut above.");
I("A glutton for punishment","يحب الصعاب","He's a glutton for punishment.");
I("A house of cards","أمر هش","Their plan was a house of cards.");
I("A labor of love","عمل بدافع الحب","The book was a labor of love.");
I("A lost cause","قضية خاسرة","This is a lost cause.");
I("A mixed blessing","نعمة بوجهين","Fame is a mixed blessing.");
I("A new lease of life","حياة جديدة","The surgery gave him a new lease of life.","UK");
I("A rolling stone","شخص متنقل","He's a rolling stone.");
I("A sight for sore eyes","منظر مفرح","You're a sight for sore eyes.");
I("A square meal","وجبة كاملة","I need a square meal.");
I("A thorn in your side","مصدر إزعاج دائم","He's a thorn in my side.");
I("A whole new ball game","وضع جديد تمامًا","Parenting is a whole new ball game.");
I("Ace up your sleeve","ورقة رابحة مخفية","He had an ace up his sleeve.");
I("Across the board","شامل","Prices rose across the board.");
I("Add up","يبدو منطقيًا","The story doesn't add up.");
I("After your own heart","يشبهك في الميول","You're a man after my own heart.");
I("All and sundry","الجميع","He invited all and sundry.");
I("All hands on deck","الجميع للعمل","It's all hands on deck.");
I("All over the place","مشتت","My schedule is all over the place.");
I("An arm and a leg","مبلغ باهظ","It cost an arm and a leg.");
I("An axe to grind","غرض شخصي","He has an axe to grind.");
I("An old hand","خبير","She's an old hand at this.");
I("As the saying goes","كما يقال","As the saying goes, patience pays.");
I("As luck would have it","من حسن الحظ","As luck would have it, I was free.");
I("At a crossroads","على مفترق طرق","I'm at a crossroads.");
I("At full tilt","بأقصى سرعة","He ran at full tilt.");
I("At loggerheads","في خلاف حاد","They're at loggerheads.");
I("At odds","في خلاف","We're at odds on this.");
I("At sea","محتار","I'm at sea with this.");
I("Back in the day","في الماضي","Back in the day, we walked.");
I("Back on track","عاد للمسار","We're back on track.");
I("Bad apple","فرد فاسد","One bad apple ruins it.");
I("Bag of tricks","مجموعة حيل","She pulled from her bag of tricks.");
I("Baptism of fire","بداية صعبة","It was a baptism of fire.");
I("Barge in","يقتحم","Don't barge in.");
I("Bark up the right tree","يسلك الطريق الصحيح","You're barking up the right tree.");
I("Basket case","شخص منهار","I'm a basket case.");
I("Bat an eyelid","يظهر ردة فعل","He didn't bat an eyelid.");
I("Be on the ball","منتبه","Be on the ball today.");
I("Bean counter","محاسب صارم","The bean counters cut costs.");
I("Bear the brunt","يتحمل الأسوأ","He bore the brunt of it.");
I("Beauty is in the eye of the beholder","الجمال نسبي","Beauty is in the eye of the beholder.");
I("Behind closed doors","سرًا","They talked behind closed doors.");
I("Below the belt","ضربة غير نزيهة","That was below the belt.");
I("Best foot forward","يظهر أفضل ما عنده","Put your best foot forward.");
I("Between you and me","بيني وبينك","Between you and me, I quit.");
I("Big cheese","شخص مهم","He's the big cheese.");
I("Bigwig","شخصية مهمة","The bigwigs attended.");
I("Bird brain","شخص غبي","Don't be a bird brain.");
I("Bite the hand that feeds","ينكر الجميل","Don't bite the hand that feeds you.");
I("Bit by bit","شيئًا فشيئًا","We saved bit by bit.");
I("Black and blue","مصاب بكدمات","I was black and blue.");
I("Blow it","يفسد الأمر","I blew it.");
I("Blow someone away","يذهله","The show blew me away.");
I("Blue blood","نبيل المولد","He has blue blood.");
I("Bolt upright","منتصب فجأة","She sat bolt upright.");
I("Bottle up","يكتم","Don't bottle it up.");
I("Break the mold","يخرج عن المألوف","She broke the mold.");
I("Bring to the table","يقدم قيمة","What do you bring to the table?");
I("Bull in a china shop","متهور","He's a bull in a china shop.");
I("Burn the candle at both ends","يرهق نفسه","She burns the candle at both ends.");
I("Bury the lede","يخفي الأهم","The article buried the lede.");
I("Butterflies in your stomach","توتر","I had butterflies in my stomach.");
I("By the book","حسب القواعد","He does everything by the book.");
I("Call it quits","يتوقف","Let's call it quits.");
I("Can of worms","مشكلة معقدة","It opened a can of worms.");
I("Cards on the table","يكشف كل شيء","Cards on the table, please.");
I("Carry a torch","يحب في صمت","He carries a torch for her.");
I("Cast in stone","ثابت","It's not cast in stone.");
I("Chance your arm","يجازف","Chance your arm and ask.","UK");
I("Chalk and cheese","مختلفان تمامًا","They're chalk and cheese.","UK");
I("Change your tune","يغير موقفه","He changed his tune.");
I("Cheat death","ينجو من الموت","He cheated death.");
I("Chew over","يفكر مليًا","Chew it over.");
I("Chicken out","يجبن","He chickened out.");
I("Clam up","يصمت فجأة","She clammed up.");
I("Clean up your act","يحسن سلوكه","Clean up your act.");
I("Clear the decks","يهيئ المكان للعمل","We cleared the decks.");
I("Close shave","نجاة بصعوبة","That was a close shave.");
I("Cloud cuckoo land","عالم الأحلام","He lives in cloud cuckoo land.","UK");
I("Cold fish","شخص بارد المشاعر","He's a cold fish.");
I("Come a cropper","يسقط أو يفشل","He came a cropper.","UK");
I("Come hell or high water","مهما حدث","I'll be there come hell or high water.");
I("Come off it","كفى!","Come off it, you're joking.");
I("Come to blows","يتشاجر","They came to blows.");
I("Come up short","يقصّر","We came up short.");
I("Cost a bomb","غالٍ جدًا","The phone cost a bomb.","UK");
I("Couch potato","كسول أمام التلفاز","He's a couch potato.");
I("Count your blessings","اشكر نعمك","Count your blessings.");
I("Crack a smile","يبتسم","He cracked a smile.");
I("Crash and burn","يفشل فشلًا ذريعًا","The startup crashed and burned.");
I("Crème de la crème","نخبة الأفضل","They're the crème de la crème.");
I("Cross your mind","يخطر على بالك","It never crossed my mind.");
I("Crying shame","عار حقيقي","It's a crying shame.");
I("Cup of joe","فنجان قهوة","I need a cup of joe.");
I("Cut a long story short","باختصار","Cut a long story short, he left.","UK");
I("Cut loose","يتحرر","Let's cut loose.");
I("Dark horse","مفاجأة","He's a dark horse.");
I("Day in, day out","كل يوم","I work day in, day out.");
I("Dead in the water","متوقف تمامًا","The plan is dead in the water.");
I("Dead ringer","شبيه تام","He's a dead ringer for his dad.");
I("Deep pockets","ثري","They have deep pockets.");
I("Dodge a bullet","ينجو من خطر","We dodged a bullet.");
I("Dog's dinner","فوضى","It was a dog's dinner.","UK");
I("Done and dusted","منتهٍ","It's done and dusted.","UK");
I("Don't rock the boat","لا تثر المشاكل","Don't rock the boat.");
I("Down to the wire","حتى اللحظة الأخيرة","It went down to the wire.");
I("Dressed to kill","أنيق جدًا","She was dressed to kill.");
I("Drive home","يؤكد","He drove the point home.");
I("Drop like flies","يسقطون بكثرة","They dropped like flies.");
I("Dry as a bone","جاف تمامًا","The soil is dry as a bone.");
I("Duck out","يتهرب","He ducked out early.");
I("Dust yourself off","ينهض بعد فشل","Dust yourself off and try again.");
I("Eagle eye","نظر حاد","She has an eagle eye.");
I("Eat like a horse","يأكل بشراهة","He eats like a horse.");
I("Egg on","يحرّض","Don't egg him on.");
I("Every now and then","من حين لآخر","I read every now and then.");
I("Eye candy","جاذبية بصرية","The ad was eye candy.");
I("Face value","القيمة الظاهرية","Take it at face value.");
I("Fall from grace","يفقد مكانته","He fell from grace.");
I("Far cry","بعيد جدًا","It's a far cry from that.");
I("Feel the heat","يشعر بالضغط","We're feeling the heat.");
I("Fiddle while Rome burns","يتجاهل الأزمة","They fiddle while Rome burns.");
I("Fighting chance","فرصة معقولة","We have a fighting chance.");
I("Fish for compliments","يستجدي المديح","She's fishing for compliments.");
I("Fit like a glove","مناسب تمامًا","It fits like a glove.");
I("Fly by the seat of your pants","يرتجل","We flew by the seat of our pants.");
I("Fool around","يعبث","Stop fooling around.");
I("For good measure","للتأكيد","He added salt for good measure.");
I("Forbidden fruit","ثمرة محرمة","It's forbidden fruit.");
I("Fork out","يدفع على مضض","I forked out fifty pounds.","UK");
I("Fresh as a daisy","نشيط","I woke up fresh as a daisy.");
I("Fly the nest","يغادر بيت الأهل","She flew the nest.");
I("From the word go","من البداية","It failed from the word go.");
I("Game changer","مغيّر قواعد اللعبة","It's a game changer.");
I("Get a life","اهتم بحياتك","Get a life!");
I("Get away with murder","ينجو بفعلته","He gets away with murder.");
I("Get in on the act","ينضم للنشاط","Everyone wanted in on the act.");
I("Get into hot water","يقع في ورطة","He got into hot water.");
I("Get your wires crossed","يسيء الفهم","We got our wires crossed.");
I("Gift of the gab","موهبة الكلام","He has the gift of the gab.");
I("Give it a rest","كفى","Give it a rest, please.");
I("Give the green light","يعطي الإذن","They gave it the green light.");
I("Go for a song","يباع بثمن بخس","It went for a song.");
I("Go it alone","يقوم بالأمر وحده","She went it alone.");
I("Go out on a limb","يخاطر برأيه","I'll go out on a limb here.");
I("Go up in smoke","يضيع","Our plans went up in smoke.");
I("Good Samaritan","فاعل خير","A good Samaritan helped.");
I("Grab a bite","يتناول وجبة سريعة","Let's grab a bite.");
I("Green around the gills","شاحب مريض","He looked green around the gills.");
I("Green thumb","موهبة في الزراعة","She has a green thumb.");
I("Grist to the mill","شيء مفيد","It's grist to the mill.","UK");
I("Gut reaction","رد فعل غريزي","My gut reaction was no.");
I("Hair of the dog","شراب لعلاج الصداع","He had a hair of the dog.","UK");
I("Hands down","بسهولة قاطعة","She won hands down.");
I("Happy camper","شخص راضٍ","I'm not a happy camper.");
I("Hard and fast","صارم","No hard and fast rules.");
I("Have a heart","ارحم","Have a heart!");
I("Have your hands full","مشغول جدًا","I have my hands full.");
I("Hear it on the grapevine","يسمعه بالشائعات","I heard it on the grapevine.");
I("Heavy heart","قلب حزين","I say this with a heavy heart.");
I("High and mighty","متعالٍ","Don't act high and mighty.");
I("Hit the hay","يذهب للنوم","I'm hitting the hay.");
I("Hit the road","ينطلق","Let's hit the road.");
I("Hold the line","يبقى ثابتًا","Hold the line, please.");
I("Home away from home","مكان مريح كالبيت","It's a home away from home.");
I("Hook, line and sinker","بتصديق كامل","He fell for it hook, line and sinker.");
I("Hot off the press","طازج","The news is hot off the press.");
I("In a flash","في لحظة","She was gone in a flash.");
I("In a jam","في مأزق","I'm in a jam.");
I("In cold blood","ببرود","He did it in cold blood.");
I("In deep water","في موقف صعب","He's in deep water.");
I("In full swing","في أوجه","The party was in full swing.");
I("In good hands","في أيد أمينة","You're in good hands.");
I("In one ear and out the other","لا يهتم","It goes in one ear and out the other.");
I("In plain sight","علنًا","It was hidden in plain sight.");
I("In the bag","مضمون","The deal is in the bag.");
I("In the driver's seat","المتحكم","She's in the driver's seat.");
I("In the same breath","في الوقت ذاته","He said both in the same breath.");
I("Itchy feet","رغبة في السفر","I've got itchy feet.");
I("Jump ship","يترك العمل","Many jumped ship.");
I("Keep a straight face","يمسك ضحكته","I couldn't keep a straight face.");
I("Keep the wolf from the door","يؤمّن معيشته","He worked to keep the wolf from the door.");
I("Know your stuff","متمكن","She knows her stuff.");
I("Knock on wood","أتمنى ألا يحدث مكروه","I'll be fine, knock on wood.");
I("Know which way the wind blows","يدرك الاتجاه السائد","He knows which way the wind blows.");
I("Let it slide","يتجاوز الأمر","I'll let it slide this time.");
I("Light a fire under someone","يحفزه","The deadline lit a fire under us.");
I("Make a killing","يربح مبلغًا كبيرًا","He made a killing in stocks.");
I("Make the cut","يتأهل","She made the cut.");
I("Mind your own business","اهتم بشؤونك","Mind your own business.");
I("Miss the mark","يخطئ الهدف","The ad missed the mark.");
I("Money talks","المال يتحكم","Money talks in this town.");
I("Move the needle","يحدث فرقًا","Will this move the needle?");
I("My two cents","رأيي المتواضع","Here's my two cents.");
I("Nail in the coffin","القشة الأخيرة للنهاية","That was the nail in the coffin.");
I("Name your poison","اختر مشروبك","Name your poison.");
I("Not born yesterday","لست ساذجًا","I wasn't born yesterday.");
I("Off your rocker","فاقد لعقله","You're off your rocker.");
