// الدفعة 6 — 100 slang + 100 idioms
S("Ballin'","يعيش حياة مترفة","He's ballin' in that car.");
S("Bamboozle","يخدع","They bamboozled me.");
S("Barf","يتقيأ","I think I'll barf.");
S("Bogus","مزيف أو سخيف","That excuse is bogus.");
S("Bomb","يفشل فشلًا ذريعًا","I bombed the test.");
S("Bookworm","محب للقراءة","She's a total bookworm.");
S("Brownie points","نقاط استحسان","He's earning brownie points.");
S("Bummed","حزين قليلًا","I'm bummed about it.");
S("Burnout","إرهاق مزمن","Work caused her burnout.");
S("Busted","مضبوط متلبسًا","Busted! You ate it.");
S("Can't even","عاجز عن التعبير من شدة الانفعال","I can't even right now.");
S("Chow","طعام","Let's get some chow.");
S("Clapback","رد حاد وذكي","Her clapback was perfect.");
S("Clingy","متعلق بشدة","He's too clingy.");
S("Cool beans","تمام / رائع","Meet at six? Cool beans.");
S("Creep","شخص مقلق التصرفات","That guy is a creep.");
S("Cutie","شخص لطيف","What a cutie!");
S("Dank","ممتاز أو طريف (إنترنت)","That's a dank meme.");
S("Deadass","بجدية","Deadass, I'm not lying.");
S("Diss","يهين","Don't diss my team.");
S("Dweeb","شخص مبتدئ اجتماعيًا","He's a harmless dweeb.");
S("Epic","مذهل","The concert was epic.");
S("Facepalm","وضع اليد على الوجه من الإحباط","That mistake made me facepalm.");
S("Fail","فشل","Epic fail!");
S("Fangirl","معجبة متحمسة","She fangirls over BTS.");
S("Flop","فشل تجاري","The film was a flop.");
S("Gassed","متحمس أو متعب حسب السياق","I'm gassed after that run.");
S("Glitch","عطل بسيط","There's a glitch in the app.");
S("Goofball","شخص مضحك وساذج","My dad's a goofball.");
S("Gross","مقرف","That smell is gross.");
S("Heck","تعبير مخفف عن hell","What the heck?");
S("Hip","عصري","It's a hip café.");
S("Hold up","انتظر","Hold up, what did you say?");
S("Hot mess","شخص أو وضع فوضوي","She's a hot mess today.");
S("Iconic","أسطوري وخالد","That scene is iconic.");
S("In my feels","غارق في مشاعره","I'm in my feels tonight.");
S("Jelly","يغار (من jealous)","I'm jelly of your trip.");
S("Juiced","متحمس وممتلئ طاقة","I'm juiced for the game.");
S("Keep it 100","يكون صادقًا","Keep it 100 with me.");
S("Kicks","أحذية رياضية","Nice kicks!");
S("Kudos","تحية وثناء","Kudos on your promotion.");
S("Main character","من يتصرف كأنه بطل القصة","She has main character energy.");
S("Meh","لا بأس / غير مبالٍ","The food was meh.");
S("Mood","يعبّر عن شعورك الحالي","Sleeping all day? Mood.");
S("Noice","نطق ممازح لـ nice","Noice work!");
S("Oof","تعبير عن الإحراج أو الألم","Oof, that hurt.");
S("Peep","ينظر","Peep this new song.");
S("Pumped","متحمس","I'm pumped for tonight.");
S("Ride or die","صديق وفي مدى الحياة","She's my ride or die.");
S("Shred","يؤدي بمهارة (تزلج، غيتار)","He shreds on guitar.");
S("Slacker","كسول","He's a slacker.");
S("Snatched","أنيق جدًا","Your outfit is snatched.");
S("Tight","قريب أو رائع","We're tight, man.");
S("Trash","سيئ جدًا","This game is trash.");
S("Turnt","في قمة الحماس","We got turnt last night.");
S("Vibing","يستمتع بالأجواء","We're just vibing.");
S("Woke","واعٍ بالقضايا الاجتماعية","He's very woke.");
S("Yikes","تعبير عن الصدمة","Yikes, that's awkward.");
S("Zen out","يهدأ ويسترخي","I zen out with music.");
S("Hop on","ينضم أو يركب","Hop on a call with us.");
S("Alright","مرحبًا أو كيف حالك؟","Alright, mate?","UK");
S("Bevvy","مشروب كحولي","Fancy a bevvy?","UK");
S("Bits and bobs","أشياء متفرقة","Just some bits and bobs.","UK");
S("Blag","يحصل على شيء بالحيلة","He blagged his way in.","UK");
S("Bog standard","عادي جدًا","It's a bog standard phone.","UK");
S("Butty","شطيرة","A bacon butty, please.","UK");
S("Cack-handed","أخرق","I'm cack-handed at cooking.","UK");
S("Chancer","شخص يجرّب حظه بجرأة","He's a right chancer.","UK");
S("Cheerio","إلى اللقاء","Cheerio, see you soon!","UK");
S("Chock-a-block","مكتظ","The road was chock-a-block.","UK");
S("Collywobbles","مغص من التوتر","I've got the collywobbles.","UK");
S("Cracking","رائع","That was a cracking game.","UK");
S("Daft","أحمق","Don't be daft.","UK");
S("Dead","جدًا","The film was dead good.","UK");
S("Div","شخص أحمق","Don't be a div.","UK");
S("Gormless","بليد","He looked gormless.","UK");
S("Jumper","سترة صوفية","Wear a jumper, it's cold.","UK");
S("Kerfuffle","جلبة وارتباك","There was a kerfuffle outside.","UK");
S("Lairy","صاخب ومستفز","He gets lairy after drinks.","UK");
S("Legless","ثمل جدًا","They were legless by ten.","UK");
S("Loo","دورة المياه","Where's the loo?","UK");
S("Manky","قذر","The sink is manky.","UK");
S("Nippy","بارد قليلًا","It's a bit nippy today.","UK");
S("Numpty","شخص أحمق","He's a total numpty.","UK");
S("Pear-shaped","سار الأمر بشكل سيئ","It all went pear-shaped.","UK");
S("Scarper","يهرب","They scarpered when the police came.","UK");
S("Snookered","محاصر بلا حل","We're snookered now.","UK");
S("Spiffing","رائع (قديم الطراز)","What a spiffing idea!","UK");
S("Sprog","طفل","Their sprog is adorable.","UK");
S("Squiffy","ثمل قليلًا","I'm feeling squiffy.","UK");
S("Tad","قليل جدًا","It's a tad cold.","UK");
S("Whinge","يتذمر","Stop whingeing!","UK");
S("Sound","جيد أو لطيف","He's a sound guy.","UK");
S("Bladdered","ثمل جدًا","We got bladdered last night.","UK");
S("Cob on","مزاج سيئ","She's got a cob on.","UK");
S("Rinse","يستنزف أو يستخدم بإفراط","He rinsed my data.","UK");
S("Whacked","منهك جدًا","I'm absolutely whacked.","UK");
S("Gutted for","يتأسف لأجل شخص","I'm gutted for you.","UK");
S("Fortnight","أسبوعان","See you in a fortnight.","UK");
S("Nosh","طعام","Let's get some nosh.","UK");
S("Tatty","رث وبالٍ","His coat looks tatty.","UK");
S("Chuffin'","تخفيف لكلمة فظة","It's chuffin' freezing.","UK");
S("Cushty","ممتاز","The job went cushty.","UK");
I("A bird in the hand","ما في اليد أفضل مما في الغيب","A bird in the hand is worth two in the bush.");
I("A hot potato","موضوع شائك","Politics is a hot potato.");
I("A leopard can't change its spots","الطبع غلب التطبع","A leopard can't change its spots.");
I("A little bird told me","سمعت ذلك من مصدر سري","A little bird told me you're moving.");
I("A storm in a teacup","ضجة حول أمر تافه","It's just a storm in a teacup.");
I("Achilles' heel","نقطة الضعف","Pride is his Achilles' heel.");
I("All bark and no bite","يهدد كثيرًا ولا ينفذ","He's all bark and no bite.");
I("The early bird catches the worm","من بكّر ظفر","Wake up! The early bird catches the worm.");
I("As the crow flies","في خط مستقيم","It's ten miles as the crow flies.");
I("Beat a dead horse","يكرر نقاشًا انتهى","Stop beating a dead horse.");
I("Better late than never","أن تصل متأخرًا خير من ألا تصل","Better late than never.");
I("Between a rock and a hard place","بين خيارين أحلاهما مر","I'm between a rock and a hard place.");
I("Bite your tongue","يمسك لسانه","I had to bite my tongue.");
I("Blood is thicker than water","رابطة العائلة أقوى","Blood is thicker than water.");
I("Blue in the face","يبذل جهدًا بلا جدوى","I argued until I was blue in the face.");
I("Born with a silver spoon","وُلد في ثراء","He was born with a silver spoon.");
I("Burn your fingers","يتضرر من تجربة","I burned my fingers investing.");
I("Bury the hatchet","ينهي الخصام","They buried the hatchet.");
I("By and large","في الغالب","By and large, it went well.");
I("Call a spade a spade","يسمي الأشياء بمسمياتها","I call a spade a spade.");
I("Carry the can","يتحمل اللوم","I had to carry the can.","UK");
I("Catnap","قيلولة قصيرة","I took a catnap.");
I("Change of heart","تغيّر الرأي","She had a change of heart.");
I("Chew the fat","يتجاذب أطراف الحديث","We chewed the fat for hours.");
I("Chickens come home to roost","العواقب تعود على صاحبها","His lies came home to roost.");
I("A clean slate","بداية جديدة","I want a clean slate.");
I("Close but no cigar","قريب لكن لم ينجح","Close but no cigar!");
I("Cold comfort","عزاء ضعيف","It was cold comfort.");
I("Come full circle","يعود إلى البداية","Life came full circle.");
I("Cool as a cucumber","هادئ جدًا","She stayed cool as a cucumber.");
I("Cost the earth","غالٍ جدًا","The ring cost the earth.","UK");
I("Crack the whip","يشدد الانضباط","The boss cracked the whip.");
I("Cry your eyes out","يبكي بشدة","She cried her eyes out.");
I("Cut it fine","يترك وقتًا ضيقًا","We cut it fine at the airport.","UK");
I("A dark horse","مرشح مفاجئ","He's the dark horse of the race.");
I("Dig your heels in","يتمسك برأيه","She dug her heels in.");
I("The dog days","أشد أيام الصيف حرًا","It's the dog days of summer.");
I("Don't give up the day job","لا تتفرغ لهذا فأنت لست جيدًا","Nice try, but don't give up the day job.");
I("A double-edged sword","سلاح ذو حدين","Fame is a double-edged sword.");
I("Drive someone up the wall","يستفزه جدًا","The noise drives me up the wall.");
I("Drop the ball","يخطئ ويهمل مسؤوليته","We dropped the ball on this.");
I("Easier said than done","القول أسهل من الفعل","Quitting is easier said than done.");
I("Eat your words","يتراجع عن كلامه","He had to eat his words.");
I("Fair and square","بنزاهة","We won fair and square.");
I("Fall on deaf ears","لا يلقى اهتمامًا","My advice fell on deaf ears.");
I("Feel the pinch","يتأثر مالياً","Families are feeling the pinch.");
I("Fight tooth and nail","يقاتل بشراسة","They fought tooth and nail.");
I("Fly off the handle","ينفعل فجأة","He flew off the handle.");
I("Follow suit","يحذو حذوه","Others will follow suit.");
I("For the time being","في الوقت الحالي","Stay here for the time being.");
I("From scratch","من الصفر","I made the cake from scratch.");
I("Get the hang of it","يتقن الأمر","I'm getting the hang of it.");
I("Get your act together","رتّب أمورك","Get your act together!");
I("Give the benefit of the doubt","يحسن الظن","Give him the benefit of the doubt.");
I("Go downhill","يتدهور","Things went downhill fast.");
I("Go Dutch","يتقاسمان الحساب","Let's go Dutch tonight.");
I("Go the distance","يكمل حتى النهاية","He went the distance.");
I("Grasp at straws","يتعلق بأي أمل","He's grasping at straws.");
I("The green light","الموافقة","We got the green light.");
I("Hand in glove","على صلة وثيقة","They work hand in glove.");
I("A hard pill to swallow","حقيقة مرة","Losing was a hard pill to swallow.");
I("Have a ball","يستمتع جدًا","We had a ball.");
I("Head over heels","واقع في الحب","He's head over heels for her.");
I("Heart of gold","قلب طيب","She has a heart of gold.");
I("High and dry","متروك بلا مساعدة","They left me high and dry.");
I("Hit rock bottom","يبلغ أسوأ حال","He hit rock bottom.");
I("Hold your tongue","اصمت","Hold your tongue!");
I("In a pickle","في ورطة","I'm in a pickle.");
I("In black and white","مكتوب بوضوح","It's there in black and white.");
I("In the dark","جاهل بالأمر","They kept me in the dark.");
I("In the nick of time","في اللحظة الأخيرة","We arrived in the nick of time.");
I("In your element","في مجالك المفضل","She's in her element on stage.");
I("Jump through hoops","يبذل جهدًا مرهقًا","I jumped through hoops for it.");
I("Keep your eyes peeled","ابق منتبهًا","Keep your eyes peeled.");
I("Kick the habit","يترك عادة","He kicked the habit.");
I("Last but not least","أخيرًا وليس آخرًا","Last but not least, thank you.");
I("Leave no stone unturned","يبذل كل جهد","We left no stone unturned.");
I("Lend an ear","يصغي","Can you lend an ear?");
I("Light at the end of the tunnel","بصيص أمل","There's light at the end of the tunnel.");
I("Like a bull in a china shop","متهور وأخرق","He moves like a bull in a china shop.");
I("Live and learn","نتعلم من التجربة","Oh well, live and learn.");
I("Look before you leap","فكّر قبل أن تتصرف","Look before you leap.");
I("Lose your marbles","يفقد عقله","Have you lost your marbles?");
I("Make a mountain out of a molehill","يضخم أمرًا بسيطًا","Don't make a mountain out of a molehill.");
I("Many hands make light work","التعاون يسهل العمل","Many hands make light work.");
I("Neck and neck","متقاربان جدًا","The race was neck and neck.");
I("Nip it in the bud","يقضي عليه في بدايته","We must nip it in the bud.");
I("No strings attached","بلا شروط","It's a gift, no strings attached.");
I("Off the record","غير رسمي","Off the record, I disagree.");
I("On the house","مجاني من المحل","The dessert is on the house.");
