// الدفعة 7 — 100 slang + 110 idioms
S("Amped","متحمس جدًا","I'm amped for the show.");
S("Badass","قوي وشجاع ومثير للإعجاب","She's a total badass.");
S("Bling","مجوهرات لامعة","Look at all that bling.");
S("Boo","الحبيب أو الحبيبة","Hey, boo!");
S("Brewski","كأس بيرة","Grab me a brewski.");
S("Buck up","تشجع","Buck up, it's not so bad.");
S("Bug out","يرحل مسرعًا أو يتوتر","We had to bug out.");
S("Bunk","كلام فارغ","That's a bunch of bunk.");
S("Burn","رد لاذع","Oh, burn!");
S("Cakewalk","أمر سهل جدًا","The exam was a cakewalk.");
S("Chad","شاب واثق ومتغطرس","He's a typical Chad.");
S("Cheat day","يوم يأكل فيه ما يشاء","Sunday is my cheat day.");
S("Chops","مهارة","He's got guitar chops.");
S("Clueless","لا يعرف شيئًا","I'm clueless about cars.");
S("Cop","يشتري","I'm gonna cop those shoes.");
S("Couch surf","يبيت عند أصدقاء مؤقتًا","He couch-surfed for a month.");
S("Cred","مصداقية","He's got street cred.");
S("Cray","مجنون (من crazy)","That's cray!");
S("Crushed it","أبلى بلاءً حسنًا","You crushed it today.");
S("Dad joke","نكتة سخيفة","That's such a dad joke.");
S("Deets","التفاصيل","Send me the deets.");
S("Dibs","أحجز لنفسي","Dibs on the front seat!");
S("Doozy","شيء استثنائي (غالبًا سيئ)","That storm was a doozy.");
S("Dub","فوز","Nice dub, team!");
S("Duds","ملابس","Cool duds, man.");
S("Fave","مفضل","This is my fave song.");
S("Feels","مشاعر قوية","That movie gave me all the feels.");
S("Fly","أنيق ومميز","You look fly today.");
S("Freebie","شيء مجاني","They gave us a freebie.");
S("Freak out","يفقد أعصابه","Don't freak out!");
S("Gig","حفلة أو عمل مؤقت","I've got a gig tonight.");
S("Glam","أنيق وفاخر","She's all glam tonight.");
S("Goober","شخص ساذج ومضحك","He's a lovable goober.");
S("Hack","حيلة ذكية","Here's a cooking hack.");
S("Hard pass","رفض قاطع","Skydiving? Hard pass.");
S("Hit different","له وقع خاص","This song hits different.");
S("Honcho","المسؤول الكبير","He's the head honcho.");
S("Hooked","مدمن أو مولع","I'm hooked on this series.");
S("Hunky-dory","على ما يرام","Everything's hunky-dory.");
S("I'm dead","أموت من الضحك","That meme? I'm dead.");
S("Jock","رياضي مولع بالرياضة","He's the school jock.");
S("Joint","مكان","This pizza joint is great.");
S("Kickback","لقاء أصدقاء غير رسمي","We're having a kickback Friday.");
S("Laid-back","مسترخٍ","She's really laid-back.");
S("Mad props","احترام وتقدير كبير","Mad props for finishing.");
S("Mansplain","يشرح بتعالٍ لأمرٍ تعرفه","He mansplained my job.");
S("Mojo","حيوية وسحر شخصي","I've lost my mojo.");
S("Moolah","مال","He's rolling in moolah.");
S("Nada","لا شيء","I found nada.");
S("Nutty","مجنون","That idea is nutty.");
S("Pal","صديق","Hey, pal!");
S("Peeps","أصدقاء وأقارب","I'm seeing my peeps tonight.");
S("Pig out","يأكل بشراهة","We pigged out on pizza.");
S("Pop off","ينفعل ويتكلم بحدة","She popped off at him.");
S("Rad","رائع","That's a rad jacket.");
S("Rando","شخص عشوائي غريب","Some rando texted me.");
S("Sass","وقاحة مرحة","Don't give me sass.");
S("Scoop","خبر حصري","Here's the scoop.");
S("Shotgun","حجز المقعد الأمامي","Shotgun!");
S("Slam dunk","نجاح مضمون","The deal is a slam dunk.");
S("Anorak","مهووس بهواية","He's a train anorak.","UK");
S("Argy-bargy","شجار وجدال","There was some argy-bargy.","UK");
S("Bap","خبز طري للشطائر","A bacon bap, please.","UK");
S("Barney","شجار","They had a big barney.","UK");
S("Biccy","بسكويت","Want a biccy?","UK");
S("Bobby","شرطي","A bobby stopped us.","UK");
S("Bonce","رأس","He bumped his bonce.","UK");
S("Bottle it","يجبن ويتراجع","He bottled it at the end.","UK");
S("Brew","شاي","Put the kettle on for a brew.","UK");
S("Cadge","يستعير ويتسول","Can I cadge a lift?","UK");
S("Chunter","يتذمر بصوت منخفض","Stop chuntering.","UK");
S("Clanger","خطأ محرج","I dropped a clanger.","UK");
S("Doolally","مجنون","He's gone doolally.","UK");
S("Earful","توبيخ طويل","She gave me an earful.","UK");
S("Elevenses","استراحة الساعة الحادية عشرة","Time for elevenses.","UK");
S("Fiver","ورقة خمسة جنيهات","Lend me a fiver.","UK");
S("Flog","يبيع","I'll flog my old bike.","UK");
S("Footie","كرة القدم","Fancy a game of footie?","UK");
S("Gaffe","زلة محرجة","It was an awful gaffe.","UK");
S("Hols","عطلة","We're off on our hols.","UK");
S("Jobsworth","موظف متشدد باللوائح","Don't be a jobsworth.","UK");
S("Lav","دورة المياه","I'm off to the lav.","UK");
S("Lolly","مال أو مصاصة","He's got loads of lolly.","UK");
S("Lurgy","مرض بسيط","I've got the lurgy.","UK");
S("Mither","يزعج","Stop mithering me.","UK");
S("Nutter","شخص مجنون","He's a harmless nutter.","UK");
S("Pillock","شخص أحمق","Don't be a pillock.","UK");
S("Pram","عربة أطفال","She pushed the pram.","UK");
S("Punter","زبون","The pub was full of punters.","UK");
S("Skedaddle","يهرب مسرعًا","Skedaddle before he sees you!","UK");
S("Snog","يقبّل","They were snogging.","UK");
S("Spud","بطاطس","Pass the spuds.","UK");
S("Starkers","عارٍ تمامًا","He ran starkers.","UK");
S("Stodge","طعام ثقيل","Pudding is pure stodge.","UK");
S("Swot","مجتهد في الدراسة","He's a bit of a swot.","UK");
S("Toff","شخص من الطبقة الراقية","He's a right toff.","UK");
S("Tuck in","يبدأ الأكل بشهية","Tuck in, everyone!","UK");
S("Uni","الجامعة","I'm off to uni.","UK");
S("Wazzock","شخص أحمق","He's a wazzock.","UK");
S("Blighter","شخص مزعج أو محظوظ","The lucky blighter won.","UK");
I("At a loose end","بلا شيء يفعله","I'm at a loose end today.");
I("At arm's length","على مسافة","Keep him at arm's length.");
I("Back the wrong horse","يراهن على الخاسر","He backed the wrong horse.");
I("Bear fruit","يؤتي ثماره","Her efforts bore fruit.");
I("Beat the clock","ينجز قبل الوقت","We beat the clock.");
I("Beggars can't be choosers","المضطر لا يختار","Beggars can't be choosers.");
I("Bend the rules","يتساهل في القواعد","Just this once, bend the rules.");
I("Bite the dust","يسقط أو يفشل","Another plan bit the dust.");
I("Blow your own trumpet","يتفاخر بنفسه","I don't like to blow my own trumpet.");
I("Blow your top","ينفجر غضبًا","He blew his top.");
I("A bolt from the blue","مفاجأة صادمة","The news was a bolt from the blue.");
I("Break even","لا يربح ولا يخسر","We just broke even.");
I("Break new ground","يفتح مجالًا جديدًا","The study broke new ground.");
I("Breathe down someone's neck","يراقبه عن كثب","Stop breathing down my neck.");
I("A bump in the road","عقبة صغيرة","It's just a bump in the road.");
I("Bust a gut","يبذل جهدًا كبيرًا","I busted a gut for this.");
I("By hook or by crook","بأي وسيلة","I'll finish it by hook or by crook.");
I("If you can't stand the heat","إن لم تتحمل فاترك","If you can't stand the heat, get out of the kitchen.");
I("A cash cow","مصدر ربح مضمون","The app is a cash cow.");
I("Catch your breath","يلتقط أنفاسه","Let me catch my breath.");
I("Chase your tail","يدور بلا فائدة","I'm just chasing my tail.");
I("Cheap as chips","رخيص جدًا","Fruit is cheap as chips here.","UK");
I("A clean bill of health","شهادة سلامة","The doctor gave him a clean bill of health.");
I("A close call","نجاة بصعوبة","That was a close call.");
I("Close ranks","يتحدون دفاعًا","The team closed ranks.");
I("The coast is clear","الطريق آمن","Go, the coast is clear.");
I("Come to terms with","يتقبل","She came to terms with it.");
I("Cook the books","يزوّر الحسابات","They cooked the books.");
I("Cool your heels","ينتظر طويلًا","I cooled my heels in the lobby.");
I("A cop-out","تهرب من المسؤولية","That answer is a cop-out.");
I("Cover your back","يحمي نفسه","Always cover your back.");
I("A crash course","دورة مكثفة","I took a crash course in French.");
I("Crocodile tears","دموع كاذبة","Those were crocodile tears.");
I("Cut and dried","محسوم وواضح","The case is cut and dried.");
I("Cut someone some slack","يتساهل معه","Cut him some slack.");
I("Daylight robbery","سعر مبالغ فيه جدًا","Ten pounds for tea is daylight robbery.","UK");
I("Dead as a doornail","ميت تمامًا","The battery is dead as a doornail.");
I("Dig deep","يبذل أقصى ما عنده","We have to dig deep.");
I("Do the trick","يحقق المطلوب","This glue should do the trick.");
I("Don't hold your breath","لا تنتظر حدوثه","Don't hold your breath.");
I("Down in the dumps","حزين","He's down in the dumps.");
I("Down the drain","ضاع هدرًا","All that money went down the drain.");
I("Draw a blank","لا يتذكر شيئًا","I drew a blank in the exam.");
I("Drive a hard bargain","يفاوض بصعوبة","She drives a hard bargain.");
I("Drop a line","يرسل رسالة","Drop me a line sometime.");
I("A dry run","تجربة تمهيدية","We did a dry run first.");
I("An eager beaver","نشيط ومتحمس","The new intern is an eager beaver.");
I("Easy does it","على مهل","Easy does it, don't rush.");
I("Eat humble pie","يعتذر ويعترف بخطئه","He had to eat humble pie.");
I("The end of the road","نهاية الطريق","This is the end of the road.");
I("Every dog has its day","لكل شخص يومه","Every dog has its day.");
I("An eye for an eye","العين بالعين","An eye for an eye leaves everyone blind.");
I("Fair game","يحق انتقاده","Politicians are fair game.");
I("Fall flat","يفشل في التأثير","His joke fell flat.");
I("Fall into place","تتضح الأمور","Everything fell into place.");
I("A feather in your cap","إنجاز يفخر به","The award is a feather in his cap.");
I("Few and far between","نادر","Good bakeries are few and far between.");
I("A fine line","فرق دقيق","There's a fine line between them.");
I("Fire away","تفضل واسأل","Fire away with your questions.");
I("First come, first served","من يأتِ أولًا يُخدم","It's first come, first served.");
I("Fit the bill","يناسب المطلوب","This candidate fits the bill.");
I("Flesh and blood","من لحمك ودمك","He's my own flesh and blood.");
I("A fly in the ointment","عيب يفسد الأمر","The cost is the fly in the ointment.");
I("Foot the bill","يدفع الحساب","Dad footed the bill.");
I("Fresh blood","دماء جديدة","The team needs fresh blood.");
I("Full of beans","مفعم بالنشاط","The kids are full of beans.");
I("Get cracking","ابدأ العمل بسرعة","Let's get cracking.");
I("Get off on the wrong foot","يبدأ بداية سيئة","We got off on the wrong foot.");
I("Get to the bottom of","يكشف السبب","I'll get to the bottom of it.");
I("Give and take","تنازلات متبادلة","Marriage is give and take.");
I("Give someone the slip","يفلت منه","The thief gave them the slip.");
I("Go haywire","يختل","The machine went haywire.");
I("Go overboard","يبالغ","Don't go overboard with spending.");
I("Go to pieces","ينهار","He went to pieces.");
I("Grin and bear it","يتحمل بصبر","You'll just have to grin and bear it.");
I("Hand over fist","بسرعة وبكثرة","They make money hand over fist.");
I("Hang by a thread","على وشك الانهيار","His job hangs by a thread.");
I("Have the upper hand","له اليد العليا","We have the upper hand.");
I("Head in the clouds","شارد الذهن","She's got her head in the clouds.");
I("A heads-up","تنبيه مسبق","Thanks for the heads-up.");
I("Hit and miss","غير مضمون","The service is hit and miss.");
I("Hold the fort","يتولى المسؤولية مؤقتًا","Can you hold the fort?");
I("Hot under the collar","غاضب","He got hot under the collar.");
I("In over your head","غارق فوق طاقته","I'm in over my head.");
I("In the red","مدين","The company is in the red.");
I("In the running","منافس بقوة","She's still in the running.");
I("In your shoes","في موقفك","I wouldn't want to be in your shoes.");
I("It's a small world","ما أصغر العالم","Wow, it's a small world!");
I("Jack of all trades","ملمّ بكل شيء","He's a jack of all trades.");
I("Keep a low profile","يبقى بعيدًا عن الأضواء","Keep a low profile for now.");
