// الدفعة 4 — تستخدم الدالتين S و I المعرّفتين في data-03.js
S("Bro","أخي / صديقي","Thanks, bro!");
S("Dude","يا رجل / يا صاحبي","Dude, you won't believe this.");
S("Bae","الحبيب أو الحبيبة","I'm having dinner with bae.");
S("Squad","مجموعة الأصدقاء","My squad is coming over.");
S("Vibe","الأجواء أو الشعور العام","I love the vibe of this place.");
S("Snack","شخص جذاب","She's a total snack.");
S("Thirsty","يبحث عن الاهتمام بشكل مبالغ فيه","Don't be so thirsty for likes.");
S("Flaky","لا يلتزم بمواعيده","He's so flaky, he cancels every time.");
S("Hella","كثير جدًا","It was hella cold last night.");
S("Ship","يتمنى ارتباط شخصين","I totally ship them.");
S("Receipts","أدلة تثبت الكلام","She posted the receipts online.");
S("Cancel","يقاطع شخصًا بعد فعل مرفوض","People tried to cancel the actor.");
S("Bruh","تعليق على موقف مخيّب أو مضحك","Bruh, you forgot the keys again?");
S("Karen","امرأة تشتكي بغرور وتطلب مقابلة المدير","Some Karen yelled at the cashier.");
S("Boomer","شخص من جيل أكبر (تُقال بسخرية)","Okay, boomer.");
S("Bop","أغنية جميلة وإيقاعها ممتع","This song is such a bop.");
S("Banger","أغنية أو حدث رائع","That track is a banger.");
S("Throwback","ذكرى من الماضي","Here's a throwback from 2015.");
S("FOMO","الخوف من تفويت الفرص","I went out because of FOMO.");
S("Catfish","ينتحل هوية مزيفة على الإنترنت","He got catfished by a fake profile.");
S("Doomscroll","يتصفح أخبارًا سيئة بلا توقف","I doomscrolled until 3 a.m.");
S("Jacked","مفتول العضلات","He's jacked from the gym.");
S("Hustle","يعمل بجد لتحقيق المال","She's got a side hustle.");
S("Grind","عمل شاق ومتواصل","Back to the grind on Monday.");
S("Hater","شخص ينتقد بحقد","Ignore the haters.");
S("Snitch","يشي بغيره","Don't be a snitch.");
S("Bounce","يغادر المكان","Let's bounce, this is boring.");
S("Crib","منزل","Nice crib, man.");
S("Bucks","دولارات","It cost fifty bucks.");
S("Dumpster fire","وضع فوضوي وكارثي","The meeting was a dumpster fire.");
S("Hot take","رأي صادم ومثير للجدل","Here's my hot take about pizza.");
S("Shook","مصدوم ومرتبك","I'm shook by the ending.");
S("Slaps","ممتاز (يُقال للطعام أو الموسيقى)","This pizza slaps.");
S("Stoked","متحمس جدًا","I'm stoked for the trip.");
S("Psyched","متحمس","She's psyched about the job.");
S("Cuppa","فنجان شاي","Fancy a cuppa?","UK");
S("Chinwag","حديث ودي","We had a good chinwag.","UK");
S("Bloke","رجل","He's a nice bloke.","UK");
S("Geezer","رجل (عامي)","That geezer helped me.","UK");
S("Gobby","كثير الكلام ووقح","Don't be so gobby.","UK");
S("Kip","قيلولة أو نوم","I need a quick kip.","UK");
S("Nick","يسرق أو يعتقل","Someone nicked my bike.","UK");
S("Pants","سيئ جدًا","The film was pants.","UK");
S("Ta","شكرًا","Ta very much!","UK");
S("Wonky","مائل وغير مستقيم","The table is wonky.","UK");
S("Barmy","مجنون","That's a barmy idea.","UK");
S("Bonkers","مجنون ومذهل","This is absolutely bonkers.","UK");
S("Mardy","متجهم ومزاجي","Stop being so mardy.","UK");
S("Skive","يتهرب من العمل أو الدراسة","He skived off school.","UK");
S("Ace","رائع","The gig was ace.","UK");
S("Brill","رائع (اختصار brilliant)","Your news is brill!","UK");
S("Trolleyed","ثمل جدًا","He was totally trolleyed.","UK");
I("Fish out of water","غريب وغير مرتاح في المكان","I felt like a fish out of water.");
I("Fall through the cracks","يُهمل دون أن ينتبه أحد","Some students fall through the cracks.");
I("Get the ball rolling","يبدأ العمل","Let's get the ball rolling.");
I("Give it a shot","يجرب","I'll give it a shot.");
I("Go back to the drawing board","يبدأ التخطيط من جديد","The plan failed, so back to the drawing board.");
I("Hold your horses","تمهّل","Hold your horses, I'm not ready.");
I("In the same boat","في الموقف نفسه","We're all in the same boat.");
I("It takes two to tango","الطرفان مسؤولان","It takes two to tango.");
I("Keep your chin up","ارفع معنوياتك","Keep your chin up, things will improve.");
I("Kick the bucket","يموت (بشكل عامي)","The old car finally kicked the bucket.");
I("Learn the ropes","يتعلم أساسيات العمل","It takes weeks to learn the ropes.");
I("Let your hair down","يرتاح ويستمتع","Come on, let your hair down.");
I("Make ends meet","يدبّر أموره المالية بصعوبة","He works two jobs to make ends meet.");
I("Money doesn't grow on trees","المال لا يأتي بسهولة","Money doesn't grow on trees.");
I("Needle in a haystack","شيء يصعب العثور عليه","Finding him is like finding a needle in a haystack.");
I("No pain, no gain","لا نجاح بلا تعب","No pain, no gain.");
I("On thin ice","في موقف خطر","You're on thin ice with the manager.");
I("Out of the woods","خرج من الخطر","The patient isn't out of the woods yet.");
I("Over the moon","سعيد جدًا","They're over the moon about the baby.");
I("Pass the buck","يلقي المسؤولية على غيره","Stop passing the buck.");
I("Pay through the nose","يدفع مبلغًا مبالغًا فيه","We paid through the nose for tickets.");
I("Pick someone's brain","يستشيره ويستفيد من خبرته","Can I pick your brain about this?");
I("Pull strings","يستخدم نفوذه","He pulled strings to get the job.");
I("Put your foot in your mouth","يقول ما يحرج","I really put my foot in my mouth.");
I("Rule of thumb","قاعدة عامة تقريبية","As a rule of thumb, save ten percent.");
I("Run out of steam","يفقد حماسه وطاقته","The team ran out of steam.");
I("Saved by the bell","أُنقذ في اللحظة الأخيرة","The class ended, so I was saved by the bell.");
I("Sleep on it","يفكر قبل أن يقرر","Let me sleep on it.");
I("Stab someone in the back","يخونه","He stabbed me in the back.");
I("Take a rain check","يؤجل الدعوة لوقت آخر","Can I take a rain check?");
I("Take the plunge","يخطو خطوة جريئة","They finally took the plunge and got married.");
I("The whole nine yards","كل شيء بالكامل","She gave us the whole nine yards.");
I("Through thick and thin","في السراء والضراء","We stayed friends through thick and thin.");
I("Time flies","الوقت يمر بسرعة","Time flies when you're having fun.");
I("Tongue in cheek","بسخرية وليس بجدية","It was a tongue-in-cheek comment.");
I("Turn a blind eye","يتغاضى عمدًا","The teacher turned a blind eye.");
I("Up in the air","غير محسوم","Our plans are still up in the air.");
I("Wild goose chase","مطاردة بلا فائدة","It was a wild goose chase.");
I("Wrap your head around","يستوعب","I can't wrap my head around it.");
I("Don't judge a book by its cover","لا تحكم من المظهر","Don't judge a book by its cover.");
I("A taste of your own medicine","يذوق ما فعله بغيره","He got a taste of his own medicine.");
I("Bad blood","عداء قديم","There's bad blood between them.");
I("Behind the scenes","في الكواليس","A lot happens behind the scenes.");
I("Big fish in a small pond","مهم في مكان صغير","He's a big fish in a small pond.");
I("Bread and butter","مصدر الرزق الأساسي","Teaching is her bread and butter.");
I("Climb the ladder","يترقى في عمله","She's climbing the corporate ladder.");
I("Cross that bridge when you come to it","نواجه المشكلة عند وقوعها","We'll cross that bridge when we come to it.");
I("Don't put all your eggs in one basket","لا تراهن على شيء واحد","Don't put all your eggs in one basket.");
I("Down to earth","متواضع وواقعي","She's very down to earth.");
