// الدفعة 2 — أضف دفعات جديدة بنفس الصيغة (data-03.js ...) ثم اربطها في index.html
EXPRESSIONS.push(
{t:"slang",en:"Sus",ar:"مشبوه",ex:"That email looks sus.",tone:"casual",reg:"US"},
{t:"slang",en:"Flex",ar:"يتباهى بما يملك",ex:"He's always flexing his new watch.",tone:"casual",reg:"US"},
{t:"slang",en:"Ghost",ar:"يقطع التواصل فجأة دون تفسير",ex:"She ghosted me after two dates.",tone:"casual",reg:"US"},
{t:"slang",en:"Slay",ar:"يتألق ويؤدي بشكل رائع",ex:"You absolutely slayed that presentation.",tone:"casual",reg:"US"},
{t:"slang",en:"Bussin'",ar:"لذيذ جدًا",ex:"This burger is bussin'.",tone:"casual",reg:"US"},
{t:"slang",en:"Ratio",ar:"أن يحصد الرد إعجابًا أكثر من المنشور الأصلي",ex:"He got ratioed for that bad take.",tone:"casual",reg:"US"},
{t:"slang",en:"Lit",ar:"ممتع ومليء بالحماس",ex:"The party last night was lit.",tone:"casual",reg:"US"},
{t:"slang",en:"Hangry",ar:"غاضب بسبب الجوع",ex:"Feed me, I'm hangry.",tone:"casual",reg:"ALL"},
{t:"slang",en:"Skint",ar:"مفلس بلا نقود",ex:"I can't come out, I'm skint this week.",tone:"casual",reg:"UK"},
{t:"slang",en:"Mate",ar:"صديقي / يا صاحبي",ex:"Cheers, mate!",tone:"casual",reg:"UK"},
{t:"slang",en:"Cheeky",ar:"وقح بشكل مرح",ex:"That was a cheeky comment.",tone:"casual",reg:"UK"},
{t:"slang",en:"Gobsmacked",ar:"مذهول تمامًا",ex:"I was gobsmacked by the news.",tone:"casual",reg:"UK"},
{t:"slang",en:"Bare",ar:"كثير جدًا (لهجة لندن)",ex:"There were bare people at the gig.",tone:"casual",reg:"UK"},
{t:"slang",en:"Dodgy",ar:"مريب أو غير موثوق",ex:"I got a dodgy feeling about that deal.",tone:"casual",reg:"UK"},
{t:"slang",en:"Cap",ar:"كذب أو مبالغة",ex:"You ran a mile? That's cap.",tone:"casual",reg:"US"},
{t:"slang",en:"Bet",ar:"اتفقنا / حسنًا",ex:"Meet at 8? Bet.",tone:"casual",reg:"US"},
{t:"idiom",en:"Bite the bullet",ar:"يتحمل أمرًا صعبًا بشجاعة",ex:"I'll just bite the bullet and call him.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Let the cat out of the bag",ar:"يكشف سرًا دون قصد",ex:"Oops, I let the cat out of the bag.",tone:"casual",reg:"ALL"},
{t:"idiom",en:"Burn the midnight oil",ar:"يسهر في العمل أو الدراسة",ex:"She burned the midnight oil before exams.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Kill two birds with one stone",ar:"يحقق هدفين بخطوة واحدة",ex:"Let's kill two birds with one stone.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Beat around the bush",ar:"يلف ويدور ولا يدخل في الموضوع",ex:"Stop beating around the bush and tell me.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Hit the nail on the head",ar:"أصاب الحقيقة تمامًا",ex:"You hit the nail on the head.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Call it a day",ar:"ينهي العمل لهذا اليوم",ex:"We're tired. Let's call it a day.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Back to square one",ar:"العودة إلى نقطة البداية",ex:"The deal failed, so it's back to square one.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Cut corners",ar:"يختصر الطريق على حساب الجودة",ex:"Don't cut corners on safety.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"On the fence",ar:"متردد لم يحسم قراره",ex:"I'm on the fence about moving.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Pull someone's leg",ar:"يمزح معه ويخدعه مازحًا",ex:"Relax, I'm just pulling your leg.",tone:"casual",reg:"ALL"},
{t:"idiom",en:"Speak of the devil",ar:"قلنا الذئب فجاء (عند ظهور من نتحدث عنه)",ex:"Speak of the devil, here he comes!",tone:"casual",reg:"ALL"},
{t:"idiom",en:"Get cold feet",ar:"يتراجع خوفًا قبل خطوة مهمة",ex:"He got cold feet before the wedding.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Go the extra mile",ar:"يبذل جهدًا إضافيًا",ex:"She always goes the extra mile.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"A blessing in disguise",ar:"نعمة في ثوب نقمة",ex:"Losing that job was a blessing in disguise.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Throw in the towel",ar:"يستسلم",ex:"I won't throw in the towel yet.",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Rain on someone's parade",ar:"يفسد عليه فرحته",ex:"I don't want to rain on your parade, but…",tone:"neutral",reg:"ALL"},
{t:"idiom",en:"Bob's your uncle",ar:"وهكذا انتهى الأمر بسهولة",ex:"Add water and Bob's your uncle.",tone:"casual",reg:"UK"},
{t:"idiom",en:"Not my cup of tea",ar:"ليس من اهتماماتي",ex:"Horror films aren't my cup of tea.",tone:"casual",reg:"UK"},
{t:"idiom",en:"Take it with a grain of salt",ar:"لا تصدقه بالكامل",ex:"Take his advice with a grain of salt.",tone:"neutral",reg:"US"}
);
